// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]


#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `google/iam/v2/policy.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

///  Data for an IAM policy.
// @@protoc_insertion_point(message:google.iam.v2.Policy)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Policy {
    // message fields
    ///  Immutable. The resource name of the `Policy`, which must be unique. Format:
    ///  `policies/{attachment_point}/denypolicies/{policy_id}`
    ///
    ///
    ///  The attachment point is identified by its URL-encoded full resource name,
    ///  which means that the forward-slash character, `/`, must be written as
    ///  `%2F`. For example,
    ///  `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-deny-policy`.
    ///
    ///  For organizations and folders, use the numeric ID in the full resource
    ///  name. For projects, requests can use the alphanumeric or the numeric ID.
    ///  Responses always contain the numeric ID.
    // @@protoc_insertion_point(field:google.iam.v2.Policy.name)
    pub name: ::std::string::String,
    ///  Immutable. The globally unique ID of the `Policy`. Assigned automatically when the
    ///  `Policy` is created.
    // @@protoc_insertion_point(field:google.iam.v2.Policy.uid)
    pub uid: ::std::string::String,
    ///  Output only. The kind of the `Policy`. Always contains the value `DenyPolicy`.
    // @@protoc_insertion_point(field:google.iam.v2.Policy.kind)
    pub kind: ::std::string::String,
    ///  A user-specified description of the `Policy`. This value can be up to 63
    ///  characters.
    // @@protoc_insertion_point(field:google.iam.v2.Policy.display_name)
    pub display_name: ::std::string::String,
    ///  A key-value map to store arbitrary metadata for the `Policy`. Keys
    ///  can be up to 63 characters. Values can be up to 255 characters.
    // @@protoc_insertion_point(field:google.iam.v2.Policy.annotations)
    pub annotations: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    ///  An opaque tag that identifies the current version of the `Policy`. IAM uses
    ///  this value to help manage concurrent updates, so they do not cause one
    ///  update to be overwritten by another.
    ///
    ///  If this field is present in a [CreatePolicy][] request, the value is
    ///  ignored.
    // @@protoc_insertion_point(field:google.iam.v2.Policy.etag)
    pub etag: ::std::string::String,
    ///  Output only. The time when the `Policy` was created.
    // @@protoc_insertion_point(field:google.iam.v2.Policy.create_time)
    pub create_time: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    ///  Output only. The time when the `Policy` was last updated.
    // @@protoc_insertion_point(field:google.iam.v2.Policy.update_time)
    pub update_time: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    ///  Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
    // @@protoc_insertion_point(field:google.iam.v2.Policy.delete_time)
    pub delete_time: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    ///  A list of rules that specify the behavior of the `Policy`. All of the rules
    ///  should be of the `kind` specified in the `Policy`.
    // @@protoc_insertion_point(field:google.iam.v2.Policy.rules)
    pub rules: ::std::vec::Vec<PolicyRule>,
    ///  Immutable. Specifies that this policy is managed by an authority and can only be
    ///  modified by that authority. Usage is restricted.
    // @@protoc_insertion_point(field:google.iam.v2.Policy.managing_authority)
    pub managing_authority: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:google.iam.v2.Policy.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Policy {
    fn default() -> &'a Policy {
        <Policy as ::protobuf::Message>::default_instance()
    }
}

impl Policy {
    pub fn new() -> Policy {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(11);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &Policy| { &m.name },
            |m: &mut Policy| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "uid",
            |m: &Policy| { &m.uid },
            |m: &mut Policy| { &mut m.uid },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "kind",
            |m: &Policy| { &m.kind },
            |m: &mut Policy| { &mut m.kind },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "display_name",
            |m: &Policy| { &m.display_name },
            |m: &mut Policy| { &mut m.display_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor::<_, _, _>(
            "annotations",
            |m: &Policy| { &m.annotations },
            |m: &mut Policy| { &mut m.annotations },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "etag",
            |m: &Policy| { &m.etag },
            |m: &mut Policy| { &mut m.etag },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "create_time",
            |m: &Policy| { &m.create_time },
            |m: &mut Policy| { &mut m.create_time },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "update_time",
            |m: &Policy| { &m.update_time },
            |m: &mut Policy| { &mut m.update_time },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "delete_time",
            |m: &Policy| { &m.delete_time },
            |m: &mut Policy| { &mut m.delete_time },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "rules",
            |m: &Policy| { &m.rules },
            |m: &mut Policy| { &mut m.rules },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "managing_authority",
            |m: &Policy| { &m.managing_authority },
            |m: &mut Policy| { &mut m.managing_authority },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Policy>(
            "Policy",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Policy {
    const NAME: &'static str = "Policy";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                18 => {
                    self.uid = is.read_string()?;
                },
                26 => {
                    self.kind = is.read_string()?;
                },
                34 => {
                    self.display_name = is.read_string()?;
                },
                42 => {
                    let len = is.read_raw_varint32()?;
                    let old_limit = is.push_limit(len as u64)?;
                    let mut key = ::std::default::Default::default();
                    let mut value = ::std::default::Default::default();
                    while let Some(tag) = is.read_raw_tag_or_eof()? {
                        match tag {
                            10 => key = is.read_string()?,
                            18 => value = is.read_string()?,
                            _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                        };
                    }
                    is.pop_limit(old_limit);
                    self.annotations.insert(key, value);
                },
                50 => {
                    self.etag = is.read_string()?;
                },
                58 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.create_time)?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.update_time)?;
                },
                74 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.delete_time)?;
                },
                82 => {
                    self.rules.push(is.read_message()?);
                },
                90 => {
                    self.managing_authority = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if !self.uid.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.uid);
        }
        if !self.kind.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.kind);
        }
        if !self.display_name.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.display_name);
        }
        for (k, v) in &self.annotations {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::string_size(2, &v);
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
        };
        if !self.etag.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.etag);
        }
        if let Some(v) = self.create_time.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.update_time.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.delete_time.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.rules {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if !self.managing_authority.is_empty() {
            my_size += ::protobuf::rt::string_size(11, &self.managing_authority);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if !self.uid.is_empty() {
            os.write_string(2, &self.uid)?;
        }
        if !self.kind.is_empty() {
            os.write_string(3, &self.kind)?;
        }
        if !self.display_name.is_empty() {
            os.write_string(4, &self.display_name)?;
        }
        for (k, v) in &self.annotations {
            let mut entry_size = 0;
            entry_size += ::protobuf::rt::string_size(1, &k);
            entry_size += ::protobuf::rt::string_size(2, &v);
            os.write_raw_varint32(42)?; // Tag.
            os.write_raw_varint32(entry_size as u32)?;
            os.write_string(1, &k)?;
            os.write_string(2, &v)?;
        };
        if !self.etag.is_empty() {
            os.write_string(6, &self.etag)?;
        }
        if let Some(v) = self.create_time.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        }
        if let Some(v) = self.update_time.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        if let Some(v) = self.delete_time.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(9, v, os)?;
        }
        for v in &self.rules {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        };
        if !self.managing_authority.is_empty() {
            os.write_string(11, &self.managing_authority)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Policy {
        Policy::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.uid.clear();
        self.kind.clear();
        self.display_name.clear();
        self.annotations.clear();
        self.etag.clear();
        self.create_time.clear();
        self.update_time.clear();
        self.delete_time.clear();
        self.rules.clear();
        self.managing_authority.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Policy {
        static instance: ::protobuf::rt::Lazy<Policy> = ::protobuf::rt::Lazy::new();
        instance.get(Policy::new)
    }
}

impl ::protobuf::MessageFull for Policy {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Policy").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Policy {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Policy {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  A single rule in a `Policy`.
// @@protoc_insertion_point(message:google.iam.v2.PolicyRule)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PolicyRule {
    // message fields
    ///  A user-specified description of the rule. This value can be up to 256
    ///  characters.
    // @@protoc_insertion_point(field:google.iam.v2.PolicyRule.description)
    pub description: ::std::string::String,
    // message oneof groups
    pub kind: ::std::option::Option<policy_rule::Kind>,
    // special fields
    // @@protoc_insertion_point(special_field:google.iam.v2.PolicyRule.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PolicyRule {
    fn default() -> &'a PolicyRule {
        <PolicyRule as ::protobuf::Message>::default_instance()
    }
}

impl PolicyRule {
    pub fn new() -> PolicyRule {
        ::std::default::Default::default()
    }

    // .google.iam.v2.DenyRule deny_rule = 2;

    pub fn deny_rule(&self) -> &super::deny::DenyRule {
        match self.kind {
            ::std::option::Option::Some(policy_rule::Kind::DenyRule(ref v)) => v,
            _ => <super::deny::DenyRule as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_deny_rule(&mut self) {
        self.kind = ::std::option::Option::None;
    }

    pub fn has_deny_rule(&self) -> bool {
        match self.kind {
            ::std::option::Option::Some(policy_rule::Kind::DenyRule(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_deny_rule(&mut self, v: super::deny::DenyRule) {
        self.kind = ::std::option::Option::Some(policy_rule::Kind::DenyRule(v))
    }

    // Mutable pointer to the field.
    pub fn mut_deny_rule(&mut self) -> &mut super::deny::DenyRule {
        if let ::std::option::Option::Some(policy_rule::Kind::DenyRule(_)) = self.kind {
        } else {
            self.kind = ::std::option::Option::Some(policy_rule::Kind::DenyRule(super::deny::DenyRule::new()));
        }
        match self.kind {
            ::std::option::Option::Some(policy_rule::Kind::DenyRule(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_deny_rule(&mut self) -> super::deny::DenyRule {
        if self.has_deny_rule() {
            match self.kind.take() {
                ::std::option::Option::Some(policy_rule::Kind::DenyRule(v)) => v,
                _ => panic!(),
            }
        } else {
            super::deny::DenyRule::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, super::deny::DenyRule>(
            "deny_rule",
            PolicyRule::has_deny_rule,
            PolicyRule::deny_rule,
            PolicyRule::mut_deny_rule,
            PolicyRule::set_deny_rule,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "description",
            |m: &PolicyRule| { &m.description },
            |m: &mut PolicyRule| { &mut m.description },
        ));
        oneofs.push(policy_rule::Kind::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PolicyRule>(
            "PolicyRule",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PolicyRule {
    const NAME: &'static str = "PolicyRule";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                18 => {
                    self.kind = ::std::option::Option::Some(policy_rule::Kind::DenyRule(is.read_message()?));
                },
                10 => {
                    self.description = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.description.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.description);
        }
        if let ::std::option::Option::Some(ref v) = self.kind {
            match v {
                &policy_rule::Kind::DenyRule(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.description.is_empty() {
            os.write_string(1, &self.description)?;
        }
        if let ::std::option::Option::Some(ref v) = self.kind {
            match v {
                &policy_rule::Kind::DenyRule(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PolicyRule {
        PolicyRule::new()
    }

    fn clear(&mut self) {
        self.kind = ::std::option::Option::None;
        self.description.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PolicyRule {
        static instance: PolicyRule = PolicyRule {
            description: ::std::string::String::new(),
            kind: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PolicyRule {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PolicyRule").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PolicyRule {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PolicyRule {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `PolicyRule`
pub mod policy_rule {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:google.iam.v2.PolicyRule.kind)
    pub enum Kind {
        // @@protoc_insertion_point(oneof_field:google.iam.v2.PolicyRule.deny_rule)
        DenyRule(super::super::deny::DenyRule),
    }

    impl ::protobuf::Oneof for Kind {
    }

    impl ::protobuf::OneofFull for Kind {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::PolicyRule as ::protobuf::MessageFull>::descriptor().oneof_by_name("kind").unwrap()).clone()
        }
    }

    impl Kind {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Kind>("kind")
        }
    }
}

///  Request message for `ListPolicies`.
// @@protoc_insertion_point(message:google.iam.v2.ListPoliciesRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ListPoliciesRequest {
    // message fields
    ///  Required. The resource that the policy is attached to, along with the kind of policy
    ///  to list. Format:
    ///  `policies/{attachment_point}/denypolicies`
    ///
    ///
    ///  The attachment point is identified by its URL-encoded full resource name,
    ///  which means that the forward-slash character, `/`, must be written as
    ///  `%2F`. For example,
    ///  `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies`.
    ///
    ///  For organizations and folders, use the numeric ID in the full resource
    ///  name. For projects, you can use the alphanumeric or the numeric ID.
    // @@protoc_insertion_point(field:google.iam.v2.ListPoliciesRequest.parent)
    pub parent: ::std::string::String,
    ///  The maximum number of policies to return. IAM ignores this value and uses
    ///  the value 1000.
    // @@protoc_insertion_point(field:google.iam.v2.ListPoliciesRequest.page_size)
    pub page_size: i32,
    ///  A page token received in a [ListPoliciesResponse][google.iam.v2.ListPoliciesResponse]. Provide this token to
    ///  retrieve the next page.
    // @@protoc_insertion_point(field:google.iam.v2.ListPoliciesRequest.page_token)
    pub page_token: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:google.iam.v2.ListPoliciesRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ListPoliciesRequest {
    fn default() -> &'a ListPoliciesRequest {
        <ListPoliciesRequest as ::protobuf::Message>::default_instance()
    }
}

impl ListPoliciesRequest {
    pub fn new() -> ListPoliciesRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "parent",
            |m: &ListPoliciesRequest| { &m.parent },
            |m: &mut ListPoliciesRequest| { &mut m.parent },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "page_size",
            |m: &ListPoliciesRequest| { &m.page_size },
            |m: &mut ListPoliciesRequest| { &mut m.page_size },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "page_token",
            |m: &ListPoliciesRequest| { &m.page_token },
            |m: &mut ListPoliciesRequest| { &mut m.page_token },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ListPoliciesRequest>(
            "ListPoliciesRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ListPoliciesRequest {
    const NAME: &'static str = "ListPoliciesRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.parent = is.read_string()?;
                },
                16 => {
                    self.page_size = is.read_int32()?;
                },
                26 => {
                    self.page_token = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.parent.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.parent);
        }
        if self.page_size != 0 {
            my_size += ::protobuf::rt::int32_size(2, self.page_size);
        }
        if !self.page_token.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.page_token);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.parent.is_empty() {
            os.write_string(1, &self.parent)?;
        }
        if self.page_size != 0 {
            os.write_int32(2, self.page_size)?;
        }
        if !self.page_token.is_empty() {
            os.write_string(3, &self.page_token)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ListPoliciesRequest {
        ListPoliciesRequest::new()
    }

    fn clear(&mut self) {
        self.parent.clear();
        self.page_size = 0;
        self.page_token.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ListPoliciesRequest {
        static instance: ListPoliciesRequest = ListPoliciesRequest {
            parent: ::std::string::String::new(),
            page_size: 0,
            page_token: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ListPoliciesRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ListPoliciesRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ListPoliciesRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ListPoliciesRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Response message for `ListPolicies`.
// @@protoc_insertion_point(message:google.iam.v2.ListPoliciesResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ListPoliciesResponse {
    // message fields
    ///  Metadata for the policies that are attached to the resource.
    // @@protoc_insertion_point(field:google.iam.v2.ListPoliciesResponse.policies)
    pub policies: ::std::vec::Vec<Policy>,
    ///  A page token that you can use in a [ListPoliciesRequest][google.iam.v2.ListPoliciesRequest] to retrieve the
    ///  next page. If this field is omitted, there are no additional pages.
    // @@protoc_insertion_point(field:google.iam.v2.ListPoliciesResponse.next_page_token)
    pub next_page_token: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:google.iam.v2.ListPoliciesResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ListPoliciesResponse {
    fn default() -> &'a ListPoliciesResponse {
        <ListPoliciesResponse as ::protobuf::Message>::default_instance()
    }
}

impl ListPoliciesResponse {
    pub fn new() -> ListPoliciesResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "policies",
            |m: &ListPoliciesResponse| { &m.policies },
            |m: &mut ListPoliciesResponse| { &mut m.policies },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "next_page_token",
            |m: &ListPoliciesResponse| { &m.next_page_token },
            |m: &mut ListPoliciesResponse| { &mut m.next_page_token },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ListPoliciesResponse>(
            "ListPoliciesResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ListPoliciesResponse {
    const NAME: &'static str = "ListPoliciesResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.policies.push(is.read_message()?);
                },
                18 => {
                    self.next_page_token = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.policies {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if !self.next_page_token.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.next_page_token);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.policies {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        if !self.next_page_token.is_empty() {
            os.write_string(2, &self.next_page_token)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ListPoliciesResponse {
        ListPoliciesResponse::new()
    }

    fn clear(&mut self) {
        self.policies.clear();
        self.next_page_token.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ListPoliciesResponse {
        static instance: ListPoliciesResponse = ListPoliciesResponse {
            policies: ::std::vec::Vec::new(),
            next_page_token: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ListPoliciesResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ListPoliciesResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ListPoliciesResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ListPoliciesResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Request message for `GetPolicy`.
// @@protoc_insertion_point(message:google.iam.v2.GetPolicyRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetPolicyRequest {
    // message fields
    ///  Required. The resource name of the policy to retrieve. Format:
    ///  `policies/{attachment_point}/denypolicies/{policy_id}`
    ///
    ///
    ///  Use the URL-encoded full resource name, which means that the forward-slash
    ///  character, `/`, must be written as `%2F`. For example,
    ///  `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-policy`.
    ///
    ///  For organizations and folders, use the numeric ID in the full resource
    ///  name. For projects, you can use the alphanumeric or the numeric ID.
    // @@protoc_insertion_point(field:google.iam.v2.GetPolicyRequest.name)
    pub name: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:google.iam.v2.GetPolicyRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GetPolicyRequest {
    fn default() -> &'a GetPolicyRequest {
        <GetPolicyRequest as ::protobuf::Message>::default_instance()
    }
}

impl GetPolicyRequest {
    pub fn new() -> GetPolicyRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &GetPolicyRequest| { &m.name },
            |m: &mut GetPolicyRequest| { &mut m.name },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GetPolicyRequest>(
            "GetPolicyRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GetPolicyRequest {
    const NAME: &'static str = "GetPolicyRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GetPolicyRequest {
        GetPolicyRequest::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GetPolicyRequest {
        static instance: GetPolicyRequest = GetPolicyRequest {
            name: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GetPolicyRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GetPolicyRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GetPolicyRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetPolicyRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Request message for `CreatePolicy`.
// @@protoc_insertion_point(message:google.iam.v2.CreatePolicyRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CreatePolicyRequest {
    // message fields
    ///  Required. The resource that the policy is attached to, along with the kind of policy
    ///  to create. Format: `policies/{attachment_point}/denypolicies`
    ///
    ///
    ///  The attachment point is identified by its URL-encoded full resource name,
    ///  which means that the forward-slash character, `/`, must be written as
    ///  `%2F`. For example,
    ///  `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies`.
    ///
    ///  For organizations and folders, use the numeric ID in the full resource
    ///  name. For projects, you can use the alphanumeric or the numeric ID.
    // @@protoc_insertion_point(field:google.iam.v2.CreatePolicyRequest.parent)
    pub parent: ::std::string::String,
    ///  Required. The policy to create.
    // @@protoc_insertion_point(field:google.iam.v2.CreatePolicyRequest.policy)
    pub policy: ::protobuf::MessageField<Policy>,
    ///  The ID to use for this policy, which will become the final component of
    ///  the policy's resource name. The ID must contain 3 to 63 characters. It can
    ///  contain lowercase letters and numbers, as well as dashes (`-`) and periods
    ///  (`.`). The first character must be a lowercase letter.
    // @@protoc_insertion_point(field:google.iam.v2.CreatePolicyRequest.policy_id)
    pub policy_id: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:google.iam.v2.CreatePolicyRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CreatePolicyRequest {
    fn default() -> &'a CreatePolicyRequest {
        <CreatePolicyRequest as ::protobuf::Message>::default_instance()
    }
}

impl CreatePolicyRequest {
    pub fn new() -> CreatePolicyRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "parent",
            |m: &CreatePolicyRequest| { &m.parent },
            |m: &mut CreatePolicyRequest| { &mut m.parent },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Policy>(
            "policy",
            |m: &CreatePolicyRequest| { &m.policy },
            |m: &mut CreatePolicyRequest| { &mut m.policy },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "policy_id",
            |m: &CreatePolicyRequest| { &m.policy_id },
            |m: &mut CreatePolicyRequest| { &mut m.policy_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CreatePolicyRequest>(
            "CreatePolicyRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CreatePolicyRequest {
    const NAME: &'static str = "CreatePolicyRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.parent = is.read_string()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.policy)?;
                },
                26 => {
                    self.policy_id = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.parent.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.parent);
        }
        if let Some(v) = self.policy.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.policy_id.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.policy_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.parent.is_empty() {
            os.write_string(1, &self.parent)?;
        }
        if let Some(v) = self.policy.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if !self.policy_id.is_empty() {
            os.write_string(3, &self.policy_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CreatePolicyRequest {
        CreatePolicyRequest::new()
    }

    fn clear(&mut self) {
        self.parent.clear();
        self.policy.clear();
        self.policy_id.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CreatePolicyRequest {
        static instance: CreatePolicyRequest = CreatePolicyRequest {
            parent: ::std::string::String::new(),
            policy: ::protobuf::MessageField::none(),
            policy_id: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CreatePolicyRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CreatePolicyRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CreatePolicyRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CreatePolicyRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Request message for `UpdatePolicy`.
// @@protoc_insertion_point(message:google.iam.v2.UpdatePolicyRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct UpdatePolicyRequest {
    // message fields
    ///  Required. The policy to update.
    ///
    ///  To prevent conflicting updates, the `etag` value must match the value that
    ///  is stored in IAM. If the `etag` values do not match, the request fails with
    ///  a `409` error code and `ABORTED` status.
    // @@protoc_insertion_point(field:google.iam.v2.UpdatePolicyRequest.policy)
    pub policy: ::protobuf::MessageField<Policy>,
    // special fields
    // @@protoc_insertion_point(special_field:google.iam.v2.UpdatePolicyRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a UpdatePolicyRequest {
    fn default() -> &'a UpdatePolicyRequest {
        <UpdatePolicyRequest as ::protobuf::Message>::default_instance()
    }
}

impl UpdatePolicyRequest {
    pub fn new() -> UpdatePolicyRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Policy>(
            "policy",
            |m: &UpdatePolicyRequest| { &m.policy },
            |m: &mut UpdatePolicyRequest| { &mut m.policy },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<UpdatePolicyRequest>(
            "UpdatePolicyRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for UpdatePolicyRequest {
    const NAME: &'static str = "UpdatePolicyRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.policy)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.policy.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.policy.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> UpdatePolicyRequest {
        UpdatePolicyRequest::new()
    }

    fn clear(&mut self) {
        self.policy.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static UpdatePolicyRequest {
        static instance: UpdatePolicyRequest = UpdatePolicyRequest {
            policy: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for UpdatePolicyRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("UpdatePolicyRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for UpdatePolicyRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UpdatePolicyRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Request message for `DeletePolicy`.
// @@protoc_insertion_point(message:google.iam.v2.DeletePolicyRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct DeletePolicyRequest {
    // message fields
    ///  Required. The resource name of the policy to delete. Format:
    ///  `policies/{attachment_point}/denypolicies/{policy_id}`
    ///
    ///
    ///  Use the URL-encoded full resource name, which means that the forward-slash
    ///  character, `/`, must be written as `%2F`. For example,
    ///  `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-policy`.
    ///
    ///  For organizations and folders, use the numeric ID in the full resource
    ///  name. For projects, you can use the alphanumeric or the numeric ID.
    // @@protoc_insertion_point(field:google.iam.v2.DeletePolicyRequest.name)
    pub name: ::std::string::String,
    ///  Optional. The expected `etag` of the policy to delete. If the value does not match
    ///  the value that is stored in IAM, the request fails with a `409` error code
    ///  and `ABORTED` status.
    ///
    ///  If you omit this field, the policy is deleted regardless of its current
    ///  `etag`.
    // @@protoc_insertion_point(field:google.iam.v2.DeletePolicyRequest.etag)
    pub etag: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:google.iam.v2.DeletePolicyRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DeletePolicyRequest {
    fn default() -> &'a DeletePolicyRequest {
        <DeletePolicyRequest as ::protobuf::Message>::default_instance()
    }
}

impl DeletePolicyRequest {
    pub fn new() -> DeletePolicyRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &DeletePolicyRequest| { &m.name },
            |m: &mut DeletePolicyRequest| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "etag",
            |m: &DeletePolicyRequest| { &m.etag },
            |m: &mut DeletePolicyRequest| { &mut m.etag },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DeletePolicyRequest>(
            "DeletePolicyRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DeletePolicyRequest {
    const NAME: &'static str = "DeletePolicyRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                18 => {
                    self.etag = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if !self.etag.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.etag);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if !self.etag.is_empty() {
            os.write_string(2, &self.etag)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DeletePolicyRequest {
        DeletePolicyRequest::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.etag.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DeletePolicyRequest {
        static instance: DeletePolicyRequest = DeletePolicyRequest {
            name: ::std::string::String::new(),
            etag: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DeletePolicyRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DeletePolicyRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DeletePolicyRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DeletePolicyRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Metadata for long-running `Policy` operations.
// @@protoc_insertion_point(message:google.iam.v2.PolicyOperationMetadata)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PolicyOperationMetadata {
    // message fields
    ///  Timestamp when the `google.longrunning.Operation` was created.
    // @@protoc_insertion_point(field:google.iam.v2.PolicyOperationMetadata.create_time)
    pub create_time: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // special fields
    // @@protoc_insertion_point(special_field:google.iam.v2.PolicyOperationMetadata.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PolicyOperationMetadata {
    fn default() -> &'a PolicyOperationMetadata {
        <PolicyOperationMetadata as ::protobuf::Message>::default_instance()
    }
}

impl PolicyOperationMetadata {
    pub fn new() -> PolicyOperationMetadata {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "create_time",
            |m: &PolicyOperationMetadata| { &m.create_time },
            |m: &mut PolicyOperationMetadata| { &mut m.create_time },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PolicyOperationMetadata>(
            "PolicyOperationMetadata",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PolicyOperationMetadata {
    const NAME: &'static str = "PolicyOperationMetadata";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.create_time)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.create_time.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.create_time.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PolicyOperationMetadata {
        PolicyOperationMetadata::new()
    }

    fn clear(&mut self) {
        self.create_time.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PolicyOperationMetadata {
        static instance: PolicyOperationMetadata = PolicyOperationMetadata {
            create_time: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PolicyOperationMetadata {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PolicyOperationMetadata").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PolicyOperationMetadata {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PolicyOperationMetadata {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1agoogle/iam/v2/policy.proto\x12\rgoogle.iam.v2\x1a\x1cgoogle/api/an\
    notations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_b\
    ehavior.proto\x1a\x18google/iam/v2/deny.proto\x1a#google/longrunning/ope\
    rations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x04\n\x06Poli\
    cy\x12\x17\n\x04name\x18\x01\x20\x01(\tR\x04nameB\x03\xe0A\x05\x12\x15\n\
    \x03uid\x18\x02\x20\x01(\tR\x03uidB\x03\xe0A\x05\x12\x17\n\x04kind\x18\
    \x03\x20\x01(\tR\x04kindB\x03\xe0A\x03\x12!\n\x0cdisplay_name\x18\x04\
    \x20\x01(\tR\x0bdisplayName\x12H\n\x0bannotations\x18\x05\x20\x03(\x0b2&\
    .google.iam.v2.Policy.AnnotationsEntryR\x0bannotations\x12\x12\n\x04etag\
    \x18\x06\x20\x01(\tR\x04etag\x12@\n\x0bcreate_time\x18\x07\x20\x01(\x0b2\
    \x1a.google.protobuf.TimestampR\ncreateTimeB\x03\xe0A\x03\x12@\n\x0bupda\
    te_time\x18\x08\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\nupdateTime\
    B\x03\xe0A\x03\x12@\n\x0bdelete_time\x18\t\x20\x01(\x0b2\x1a.google.prot\
    obuf.TimestampR\ndeleteTimeB\x03\xe0A\x03\x12/\n\x05rules\x18\n\x20\x03(\
    \x0b2\x19.google.iam.v2.PolicyRuleR\x05rules\x122\n\x12managing_authorit\
    y\x18\x0b\x20\x01(\tR\x11managingAuthorityB\x03\xe0A\x05\x1a>\n\x10Annot\
    ationsEntry\x12\x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x12\x14\n\x05val\
    ue\x18\x02\x20\x01(\tR\x05value:\x028\x01\"n\n\nPolicyRule\x126\n\tdeny_\
    rule\x18\x02\x20\x01(\x0b2\x17.google.iam.v2.DenyRuleH\0R\x08denyRule\
    \x12\x20\n\x0bdescription\x18\x01\x20\x01(\tR\x0bdescriptionB\x06\n\x04k\
    ind\"n\n\x13ListPoliciesRequest\x12\x1b\n\x06parent\x18\x01\x20\x01(\tR\
    \x06parentB\x03\xe0A\x02\x12\x1b\n\tpage_size\x18\x02\x20\x01(\x05R\x08p\
    ageSize\x12\x1d\n\npage_token\x18\x03\x20\x01(\tR\tpageToken\"q\n\x14Lis\
    tPoliciesResponse\x121\n\x08policies\x18\x01\x20\x03(\x0b2\x15.google.ia\
    m.v2.PolicyR\x08policies\x12&\n\x0fnext_page_token\x18\x02\x20\x01(\tR\r\
    nextPageToken\"+\n\x10GetPolicyRequest\x12\x17\n\x04name\x18\x01\x20\x01\
    (\tR\x04nameB\x03\xe0A\x02\"\x83\x01\n\x13CreatePolicyRequest\x12\x1b\n\
    \x06parent\x18\x01\x20\x01(\tR\x06parentB\x03\xe0A\x02\x122\n\x06policy\
    \x18\x02\x20\x01(\x0b2\x15.google.iam.v2.PolicyR\x06policyB\x03\xe0A\x02\
    \x12\x1b\n\tpolicy_id\x18\x03\x20\x01(\tR\x08policyId\"I\n\x13UpdatePoli\
    cyRequest\x122\n\x06policy\x18\x01\x20\x01(\x0b2\x15.google.iam.v2.Polic\
    yR\x06policyB\x03\xe0A\x02\"G\n\x13DeletePolicyRequest\x12\x17\n\x04name\
    \x18\x01\x20\x01(\tR\x04nameB\x03\xe0A\x02\x12\x17\n\x04etag\x18\x02\x20\
    \x01(\tR\x04etagB\x03\xe0A\x01\"V\n\x17PolicyOperationMetadata\x12;\n\
    \x0bcreate_time\x18\x01\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\ncr\
    eateTime2\xd0\x06\n\x08Policies\x12\x83\x01\n\x0cListPolicies\x12\".goog\
    le.iam.v2.ListPoliciesRequest\x1a#.google.iam.v2.ListPoliciesResponse\"*\
    \x82\xd3\xe4\x93\x02\x1b\x12\x19/v2/{parent=policies/*/*}\xdaA\x06parent\
    \x12m\n\tGetPolicy\x12\x1f.google.iam.v2.GetPolicyRequest\x1a\x15.google\
    .iam.v2.Policy\"(\x82\xd3\xe4\x93\x02\x1b\x12\x19/v2/{name=policies/*/*/\
    *}\xdaA\x04name\x12\xba\x01\n\x0cCreatePolicy\x12\".google.iam.v2.Create\
    PolicyRequest\x1a\x1d.google.longrunning.Operation\"g\xcaA!\n\x06Policy\
    \x12\x17PolicyOperationMetadata\x82\xd3\xe4\x93\x02#\"\x19/v2/{parent=po\
    licies/*/*}:\x06policy\xdaA\x17parent,policy,policy_id\x12\xa7\x01\n\x0c\
    UpdatePolicy\x12\".google.iam.v2.UpdatePolicyRequest\x1a\x1d.google.long\
    running.Operation\"T\xcaA!\n\x06Policy\x12\x17PolicyOperationMetadata\
    \x82\xd3\xe4\x93\x02*\x1a\x20/v2/{policy.name=policies/*/*/*}:\x06policy\
    \x12\x9f\x01\n\x0cDeletePolicy\x12\".google.iam.v2.DeletePolicyRequest\
    \x1a\x1d.google.longrunning.Operation\"L\xcaA!\n\x06Policy\x12\x17Policy\
    OperationMetadata\x82\xd3\xe4\x93\x02\x1b*\x19/v2/{name=policies/*/*/*}\
    \xdaA\x04name\x1aF\xd2A.https://www.googleapis.com/auth/cloud-platform\
    \xcaA\x12iam.googleapis.comBy\n\x11com.google.iam.v2B\x0bPolicyProtoP\
    \x01Z)cloud.google.com/go/iam/apiv2/iampb;iampb\xaa\x02\x13Google.Cloud.\
    Iam.V2\xca\x02\x13Google\\Cloud\\Iam\\V2J\xfbO\n\x07\x12\x05\x0e\0\x9e\
    \x02\x01\n\xbc\x04\n\x01\x0c\x12\x03\x0e\0\x122\xb1\x04\x20Copyright\x20\
    2024\x20Google\x20LLC\n\n\x20Licensed\x20under\x20the\x20Apache\x20Licen\
    se,\x20Version\x202.0\x20(the\x20\"License\");\n\x20you\x20may\x20not\
    \x20use\x20this\x20file\x20except\x20in\x20compliance\x20with\x20the\x20\
    License.\n\x20You\x20may\x20obtain\x20a\x20copy\x20of\x20the\x20License\
    \x20at\n\n\x20\x20\x20\x20\x20http://www.apache.org/licenses/LICENSE-2.0\
    \n\n\x20Unless\x20required\x20by\x20applicable\x20law\x20or\x20agreed\
    \x20to\x20in\x20writing,\x20software\n\x20distributed\x20under\x20the\
    \x20License\x20is\x20distributed\x20on\x20an\x20\"AS\x20IS\"\x20BASIS,\n\
    \x20WITHOUT\x20WARRANTIES\x20OR\x20CONDITIONS\x20OF\x20ANY\x20KIND,\x20e\
    ither\x20express\x20or\x20implied.\n\x20See\x20the\x20License\x20for\x20\
    the\x20specific\x20language\x20governing\x20permissions\x20and\n\x20limi\
    tations\x20under\x20the\x20License.\n\n\x08\n\x01\x02\x12\x03\x10\0\x16\
    \n\t\n\x02\x03\0\x12\x03\x12\0&\n\t\n\x02\x03\x01\x12\x03\x13\0!\n\t\n\
    \x02\x03\x02\x12\x03\x14\0)\n\t\n\x02\x03\x03\x12\x03\x15\0\"\n\t\n\x02\
    \x03\x04\x12\x03\x16\0-\n\t\n\x02\x03\x05\x12\x03\x17\0)\n\x08\n\x01\x08\
    \x12\x03\x19\00\n\t\n\x02\x08%\x12\x03\x19\00\n\x08\n\x01\x08\x12\x03\
    \x1a\0@\n\t\n\x02\x08\x0b\x12\x03\x1a\0@\n\x08\n\x01\x08\x12\x03\x1b\0\"\
    \n\t\n\x02\x08\n\x12\x03\x1b\0\"\n\x08\n\x01\x08\x12\x03\x1c\0,\n\t\n\
    \x02\x08\x08\x12\x03\x1c\0,\n\x08\n\x01\x08\x12\x03\x1d\0*\n\t\n\x02\x08\
    \x01\x12\x03\x1d\0*\n\x08\n\x01\x08\x12\x03\x1e\00\n\t\n\x02\x08)\x12\
    \x03\x1e\00\nV\n\x02\x06\0\x12\x04!\0g\x01\x1aJ\x20An\x20interface\x20fo\
    r\x20managing\x20Identity\x20and\x20Access\x20Management\x20(IAM)\x20pol\
    icies.\n\n\n\n\x03\x06\0\x01\x12\x03!\x08\x10\n\n\n\x03\x06\0\x03\x12\
    \x03\"\x02:\n\x0c\n\x05\x06\0\x03\x99\x08\x12\x03\"\x02:\n\n\n\x03\x06\0\
    \x03\x12\x03#\x02V\n\x0c\n\x05\x06\0\x03\x9a\x08\x12\x03#\x02V\n\xb4\x01\
    \n\x04\x06\0\x02\0\x12\x04*\x02/\x03\x1a\xa5\x01\x20Retrieves\x20the\x20\
    policies\x20of\x20the\x20specified\x20kind\x20that\x20are\x20attached\
    \x20to\x20a\n\x20resource.\n\n\x20The\x20response\x20lists\x20only\x20po\
    licy\x20metadata.\x20In\x20particular,\x20policy\x20rules\x20are\n\x20om\
    itted.\n\n\x0c\n\x05\x06\0\x02\0\x01\x12\x03*\x06\x12\n\x0c\n\x05\x06\0\
    \x02\0\x02\x12\x03*\x13&\n\x0c\n\x05\x06\0\x02\0\x03\x12\x03*1E\n\r\n\
    \x05\x06\0\x02\0\x04\x12\x04+\x04-\x06\n\x11\n\t\x06\0\x02\0\x04\xb0\xca\
    \xbc\"\x12\x04+\x04-\x06\n\x0c\n\x05\x06\0\x02\0\x04\x12\x03.\x044\n\x0f\
    \n\x08\x06\0\x02\0\x04\x9b\x08\0\x12\x03.\x044\n\x1e\n\x04\x06\0\x02\x01\
    \x12\x042\x027\x03\x1a\x10\x20Gets\x20a\x20policy.\n\n\x0c\n\x05\x06\0\
    \x02\x01\x01\x12\x032\x06\x0f\n\x0c\n\x05\x06\0\x02\x01\x02\x12\x032\x10\
    \x20\n\x0c\n\x05\x06\0\x02\x01\x03\x12\x032+1\n\r\n\x05\x06\0\x02\x01\
    \x04\x12\x043\x045\x06\n\x11\n\t\x06\0\x02\x01\x04\xb0\xca\xbc\"\x12\x04\
    3\x045\x06\n\x0c\n\x05\x06\0\x02\x01\x04\x12\x036\x042\n\x0f\n\x08\x06\0\
    \x02\x01\x04\x9b\x08\0\x12\x036\x042\n!\n\x04\x06\0\x02\x02\x12\x04:\x02\
    D\x03\x1a\x13\x20Creates\x20a\x20policy.\n\n\x0c\n\x05\x06\0\x02\x02\x01\
    \x12\x03:\x06\x12\n\x0c\n\x05\x06\0\x02\x02\x02\x12\x03:\x13&\n\x0c\n\
    \x05\x06\0\x02\x02\x03\x12\x03:1M\n\r\n\x05\x06\0\x02\x02\x04\x12\x04;\
    \x04>\x06\n\x11\n\t\x06\0\x02\x02\x04\xb0\xca\xbc\"\x12\x04;\x04>\x06\n\
    \x0c\n\x05\x06\0\x02\x02\x04\x12\x03?\x04E\n\x0f\n\x08\x06\0\x02\x02\x04\
    \x9b\x08\0\x12\x03?\x04E\n\r\n\x05\x06\0\x02\x02\x04\x12\x04@\x04C\x06\n\
    \x0f\n\x07\x06\0\x02\x02\x04\x99\x08\x12\x04@\x04C\x06\n\xac\x03\n\x04\
    \x06\0\x02\x03\x12\x04Q\x02Z\x03\x1a\x9d\x03\x20Updates\x20the\x20specif\
    ied\x20policy.\n\n\x20You\x20can\x20update\x20only\x20the\x20rules\x20an\
    d\x20the\x20display\x20name\x20for\x20the\x20policy.\n\n\x20To\x20update\
    \x20a\x20policy,\x20you\x20should\x20use\x20a\x20read-modify-write\x20lo\
    op:\n\n\x201.\x20Use\x20[GetPolicy][google.iam.v2.Policies.GetPolicy]\
    \x20to\x20read\x20the\x20current\x20version\x20of\x20the\x20policy.\n\
    \x202.\x20Modify\x20the\x20policy\x20as\x20needed.\n\x203.\x20Use\x20`Up\
    datePolicy`\x20to\x20write\x20the\x20updated\x20policy.\n\n\x20This\x20p\
    attern\x20helps\x20prevent\x20conflicts\x20between\x20concurrent\x20upda\
    tes.\n\n\x0c\n\x05\x06\0\x02\x03\x01\x12\x03Q\x06\x12\n\x0c\n\x05\x06\0\
    \x02\x03\x02\x12\x03Q\x13&\n\x0c\n\x05\x06\0\x02\x03\x03\x12\x03Q1M\n\r\
    \n\x05\x06\0\x02\x03\x04\x12\x04R\x04U\x06\n\x11\n\t\x06\0\x02\x03\x04\
    \xb0\xca\xbc\"\x12\x04R\x04U\x06\n\r\n\x05\x06\0\x02\x03\x04\x12\x04V\
    \x04Y\x06\n\x0f\n\x07\x06\0\x02\x03\x04\x99\x08\x12\x04V\x04Y\x06\n;\n\
    \x04\x06\0\x02\x04\x12\x04]\x02f\x03\x1a-\x20Deletes\x20a\x20policy.\x20\
    This\x20action\x20is\x20permanent.\n\n\x0c\n\x05\x06\0\x02\x04\x01\x12\
    \x03]\x06\x12\n\x0c\n\x05\x06\0\x02\x04\x02\x12\x03]\x13&\n\x0c\n\x05\
    \x06\0\x02\x04\x03\x12\x03]1M\n\r\n\x05\x06\0\x02\x04\x04\x12\x04^\x04`\
    \x06\n\x11\n\t\x06\0\x02\x04\x04\xb0\xca\xbc\"\x12\x04^\x04`\x06\n\x0c\n\
    \x05\x06\0\x02\x04\x04\x12\x03a\x042\n\x0f\n\x08\x06\0\x02\x04\x04\x9b\
    \x08\0\x12\x03a\x042\n\r\n\x05\x06\0\x02\x04\x04\x12\x04b\x04e\x06\n\x0f\
    \n\x07\x06\0\x02\x04\x04\x99\x08\x12\x04b\x04e\x06\n&\n\x02\x04\0\x12\
    \x05j\0\xa0\x01\x01\x1a\x19\x20Data\x20for\x20an\x20IAM\x20policy.\n\n\n\
    \n\x03\x04\0\x01\x12\x03j\x08\x0e\n\xde\x04\n\x04\x04\0\x02\0\x12\x03w\
    \x02<\x1a\xd0\x04\x20Immutable.\x20The\x20resource\x20name\x20of\x20the\
    \x20`Policy`,\x20which\x20must\x20be\x20unique.\x20Format:\n\x20`policie\
    s/{attachment_point}/denypolicies/{policy_id}`\n\n\n\x20The\x20attachmen\
    t\x20point\x20is\x20identified\x20by\x20its\x20URL-encoded\x20full\x20re\
    source\x20name,\n\x20which\x20means\x20that\x20the\x20forward-slash\x20c\
    haracter,\x20`/`,\x20must\x20be\x20written\x20as\n\x20`%2F`.\x20For\x20e\
    xample,\n\x20`policies/cloudresourcemanager.googleapis.com%2Fprojects%2F\
    my-project/denypolicies/my-deny-policy`.\n\n\x20For\x20organizations\x20\
    and\x20folders,\x20use\x20the\x20numeric\x20ID\x20in\x20the\x20full\x20r\
    esource\n\x20name.\x20For\x20projects,\x20requests\x20can\x20use\x20the\
    \x20alphanumeric\x20or\x20the\x20numeric\x20ID.\n\x20Responses\x20always\
    \x20contain\x20the\x20numeric\x20ID.\n\n\x0c\n\x05\x04\0\x02\0\x05\x12\
    \x03w\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03w\t\r\n\x0c\n\x05\x04\0\
    \x02\0\x03\x12\x03w\x10\x11\n\x0c\n\x05\x04\0\x02\0\x08\x12\x03w\x12;\n\
    \x0f\n\x08\x04\0\x02\0\x08\x9c\x08\0\x12\x03w\x13:\nw\n\x04\x04\0\x02\
    \x01\x12\x03{\x02;\x1aj\x20Immutable.\x20The\x20globally\x20unique\x20ID\
    \x20of\x20the\x20`Policy`.\x20Assigned\x20automatically\x20when\x20the\n\
    \x20`Policy`\x20is\x20created.\n\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03{\
    \x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03{\t\x0c\n\x0c\n\x05\x04\0\
    \x02\x01\x03\x12\x03{\x0f\x10\n\x0c\n\x05\x04\0\x02\x01\x08\x12\x03{\x11\
    :\n\x0f\n\x08\x04\0\x02\x01\x08\x9c\x08\0\x12\x03{\x129\n]\n\x04\x04\0\
    \x02\x02\x12\x03~\x02>\x1aP\x20Output\x20only.\x20The\x20kind\x20of\x20t\
    he\x20`Policy`.\x20Always\x20contains\x20the\x20value\x20`DenyPolicy`.\n\
    \n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03~\x02\x08\n\x0c\n\x05\x04\0\x02\
    \x02\x01\x12\x03~\t\r\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03~\x10\x11\n\
    \x0c\n\x05\x04\0\x02\x02\x08\x12\x03~\x12=\n\x0f\n\x08\x04\0\x02\x02\x08\
    \x9c\x08\0\x12\x03~\x13<\ne\n\x04\x04\0\x02\x03\x12\x04\x82\x01\x02\x1a\
    \x1aW\x20A\x20user-specified\x20description\x20of\x20the\x20`Policy`.\
    \x20This\x20value\x20can\x20be\x20up\x20to\x2063\n\x20characters.\n\n\r\
    \n\x05\x04\0\x02\x03\x05\x12\x04\x82\x01\x02\x08\n\r\n\x05\x04\0\x02\x03\
    \x01\x12\x04\x82\x01\t\x15\n\r\n\x05\x04\0\x02\x03\x03\x12\x04\x82\x01\
    \x18\x19\n\x94\x01\n\x04\x04\0\x02\x04\x12\x04\x86\x01\x02&\x1a\x85\x01\
    \x20A\x20key-value\x20map\x20to\x20store\x20arbitrary\x20metadata\x20for\
    \x20the\x20`Policy`.\x20Keys\n\x20can\x20be\x20up\x20to\x2063\x20charact\
    ers.\x20Values\x20can\x20be\x20up\x20to\x20255\x20characters.\n\n\r\n\
    \x05\x04\0\x02\x04\x06\x12\x04\x86\x01\x02\x15\n\r\n\x05\x04\0\x02\x04\
    \x01\x12\x04\x86\x01\x16!\n\r\n\x05\x04\0\x02\x04\x03\x12\x04\x86\x01$%\
    \n\x9b\x02\n\x04\x04\0\x02\x05\x12\x04\x8e\x01\x02\x12\x1a\x8c\x02\x20An\
    \x20opaque\x20tag\x20that\x20identifies\x20the\x20current\x20version\x20\
    of\x20the\x20`Policy`.\x20IAM\x20uses\n\x20this\x20value\x20to\x20help\
    \x20manage\x20concurrent\x20updates,\x20so\x20they\x20do\x20not\x20cause\
    \x20one\n\x20update\x20to\x20be\x20overwritten\x20by\x20another.\n\n\x20\
    If\x20this\x20field\x20is\x20present\x20in\x20a\x20[CreatePolicy][]\x20r\
    equest,\x20the\x20value\x20is\n\x20ignored.\n\n\r\n\x05\x04\0\x02\x05\
    \x05\x12\x04\x8e\x01\x02\x08\n\r\n\x05\x04\0\x02\x05\x01\x12\x04\x8e\x01\
    \t\r\n\r\n\x05\x04\0\x02\x05\x03\x12\x04\x8e\x01\x10\x11\nD\n\x04\x04\0\
    \x02\x06\x12\x04\x91\x01\x02X\x1a6\x20Output\x20only.\x20The\x20time\x20\
    when\x20the\x20`Policy`\x20was\x20created.\n\n\r\n\x05\x04\0\x02\x06\x06\
    \x12\x04\x91\x01\x02\x1b\n\r\n\x05\x04\0\x02\x06\x01\x12\x04\x91\x01\x1c\
    '\n\r\n\x05\x04\0\x02\x06\x03\x12\x04\x91\x01*+\n\r\n\x05\x04\0\x02\x06\
    \x08\x12\x04\x91\x01,W\n\x10\n\x08\x04\0\x02\x06\x08\x9c\x08\0\x12\x04\
    \x91\x01-V\nI\n\x04\x04\0\x02\x07\x12\x04\x94\x01\x02X\x1a;\x20Output\
    \x20only.\x20The\x20time\x20when\x20the\x20`Policy`\x20was\x20last\x20up\
    dated.\n\n\r\n\x05\x04\0\x02\x07\x06\x12\x04\x94\x01\x02\x1b\n\r\n\x05\
    \x04\0\x02\x07\x01\x12\x04\x94\x01\x1c'\n\r\n\x05\x04\0\x02\x07\x03\x12\
    \x04\x94\x01*+\n\r\n\x05\x04\0\x02\x07\x08\x12\x04\x94\x01,W\n\x10\n\x08\
    \x04\0\x02\x07\x08\x9c\x08\0\x12\x04\x94\x01-V\nh\n\x04\x04\0\x02\x08\
    \x12\x04\x97\x01\x02X\x1aZ\x20Output\x20only.\x20The\x20time\x20when\x20\
    the\x20`Policy`\x20was\x20deleted.\x20Empty\x20if\x20the\x20policy\x20is\
    \x20not\x20deleted.\n\n\r\n\x05\x04\0\x02\x08\x06\x12\x04\x97\x01\x02\
    \x1b\n\r\n\x05\x04\0\x02\x08\x01\x12\x04\x97\x01\x1c'\n\r\n\x05\x04\0\
    \x02\x08\x03\x12\x04\x97\x01*+\n\r\n\x05\x04\0\x02\x08\x08\x12\x04\x97\
    \x01,W\n\x10\n\x08\x04\0\x02\x08\x08\x9c\x08\0\x12\x04\x97\x01-V\n\x90\
    \x01\n\x04\x04\0\x02\t\x12\x04\x9b\x01\x02!\x1a\x81\x01\x20A\x20list\x20\
    of\x20rules\x20that\x20specify\x20the\x20behavior\x20of\x20the\x20`Polic\
    y`.\x20All\x20of\x20the\x20rules\n\x20should\x20be\x20of\x20the\x20`kind\
    `\x20specified\x20in\x20the\x20`Policy`.\n\n\r\n\x05\x04\0\x02\t\x04\x12\
    \x04\x9b\x01\x02\n\n\r\n\x05\x04\0\x02\t\x06\x12\x04\x9b\x01\x0b\x15\n\r\
    \n\x05\x04\0\x02\t\x01\x12\x04\x9b\x01\x16\x1b\n\r\n\x05\x04\0\x02\t\x03\
    \x12\x04\x9b\x01\x1e\x20\n\x93\x01\n\x04\x04\0\x02\n\x12\x04\x9f\x01\x02\
    K\x1a\x84\x01\x20Immutable.\x20Specifies\x20that\x20this\x20policy\x20is\
    \x20managed\x20by\x20an\x20authority\x20and\x20can\x20only\x20be\n\x20mo\
    dified\x20by\x20that\x20authority.\x20Usage\x20is\x20restricted.\n\n\r\n\
    \x05\x04\0\x02\n\x05\x12\x04\x9f\x01\x02\x08\n\r\n\x05\x04\0\x02\n\x01\
    \x12\x04\x9f\x01\t\x1b\n\r\n\x05\x04\0\x02\n\x03\x12\x04\x9f\x01\x1e\x20\
    \n\r\n\x05\x04\0\x02\n\x08\x12\x04\x9f\x01!J\n\x10\n\x08\x04\0\x02\n\x08\
    \x9c\x08\0\x12\x04\x9f\x01\"I\n,\n\x02\x04\x01\x12\x06\xa3\x01\0\xac\x01\
    \x01\x1a\x1e\x20A\x20single\x20rule\x20in\x20a\x20`Policy`.\n\n\x0b\n\
    \x03\x04\x01\x01\x12\x04\xa3\x01\x08\x12\n\x0e\n\x04\x04\x01\x08\0\x12\
    \x06\xa4\x01\x02\xa7\x01\x03\n\r\n\x05\x04\x01\x08\0\x01\x12\x04\xa4\x01\
    \x08\x0c\n)\n\x04\x04\x01\x02\0\x12\x04\xa6\x01\x04\x1b\x1a\x1b\x20A\x20\
    rule\x20for\x20a\x20deny\x20policy.\n\n\r\n\x05\x04\x01\x02\0\x06\x12\
    \x04\xa6\x01\x04\x0c\n\r\n\x05\x04\x01\x02\0\x01\x12\x04\xa6\x01\r\x16\n\
    \r\n\x05\x04\x01\x02\0\x03\x12\x04\xa6\x01\x19\x1a\nb\n\x04\x04\x01\x02\
    \x01\x12\x04\xab\x01\x02\x19\x1aT\x20A\x20user-specified\x20description\
    \x20of\x20the\x20rule.\x20This\x20value\x20can\x20be\x20up\x20to\x20256\
    \n\x20characters.\n\n\r\n\x05\x04\x01\x02\x01\x05\x12\x04\xab\x01\x02\
    \x08\n\r\n\x05\x04\x01\x02\x01\x01\x12\x04\xab\x01\t\x14\n\r\n\x05\x04\
    \x01\x02\x01\x03\x12\x04\xab\x01\x17\x18\n3\n\x02\x04\x02\x12\x06\xaf\
    \x01\0\xc5\x01\x01\x1a%\x20Request\x20message\x20for\x20`ListPolicies`.\
    \n\n\x0b\n\x03\x04\x02\x01\x12\x04\xaf\x01\x08\x1b\n\xb0\x04\n\x04\x04\
    \x02\x02\0\x12\x04\xbc\x01\x02=\x1a\xa1\x04\x20Required.\x20The\x20resou\
    rce\x20that\x20the\x20policy\x20is\x20attached\x20to,\x20along\x20with\
    \x20the\x20kind\x20of\x20policy\n\x20to\x20list.\x20Format:\n\x20`polici\
    es/{attachment_point}/denypolicies`\n\n\n\x20The\x20attachment\x20point\
    \x20is\x20identified\x20by\x20its\x20URL-encoded\x20full\x20resource\x20\
    name,\n\x20which\x20means\x20that\x20the\x20forward-slash\x20character,\
    \x20`/`,\x20must\x20be\x20written\x20as\n\x20`%2F`.\x20For\x20example,\n\
    \x20`policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-projec\
    t/denypolicies`.\n\n\x20For\x20organizations\x20and\x20folders,\x20use\
    \x20the\x20numeric\x20ID\x20in\x20the\x20full\x20resource\n\x20name.\x20\
    For\x20projects,\x20you\x20can\x20use\x20the\x20alphanumeric\x20or\x20th\
    e\x20numeric\x20ID.\n\n\r\n\x05\x04\x02\x02\0\x05\x12\x04\xbc\x01\x02\
    \x08\n\r\n\x05\x04\x02\x02\0\x01\x12\x04\xbc\x01\t\x0f\n\r\n\x05\x04\x02\
    \x02\0\x03\x12\x04\xbc\x01\x12\x13\n\r\n\x05\x04\x02\x02\0\x08\x12\x04\
    \xbc\x01\x14<\n\x10\n\x08\x04\x02\x02\0\x08\x9c\x08\0\x12\x04\xbc\x01\
    \x15;\nj\n\x04\x04\x02\x02\x01\x12\x04\xc0\x01\x02\x16\x1a\\\x20The\x20m\
    aximum\x20number\x20of\x20policies\x20to\x20return.\x20IAM\x20ignores\
    \x20this\x20value\x20and\x20uses\n\x20the\x20value\x201000.\n\n\r\n\x05\
    \x04\x02\x02\x01\x05\x12\x04\xc0\x01\x02\x07\n\r\n\x05\x04\x02\x02\x01\
    \x01\x12\x04\xc0\x01\x08\x11\n\r\n\x05\x04\x02\x02\x01\x03\x12\x04\xc0\
    \x01\x14\x15\n\x96\x01\n\x04\x04\x02\x02\x02\x12\x04\xc4\x01\x02\x18\x1a\
    \x87\x01\x20A\x20page\x20token\x20received\x20in\x20a\x20[ListPoliciesRe\
    sponse][google.iam.v2.ListPoliciesResponse].\x20Provide\x20this\x20token\
    \x20to\n\x20retrieve\x20the\x20next\x20page.\n\n\r\n\x05\x04\x02\x02\x02\
    \x05\x12\x04\xc4\x01\x02\x08\n\r\n\x05\x04\x02\x02\x02\x01\x12\x04\xc4\
    \x01\t\x13\n\r\n\x05\x04\x02\x02\x02\x03\x12\x04\xc4\x01\x16\x17\n4\n\
    \x02\x04\x03\x12\x06\xc8\x01\0\xcf\x01\x01\x1a&\x20Response\x20message\
    \x20for\x20`ListPolicies`.\n\n\x0b\n\x03\x04\x03\x01\x12\x04\xc8\x01\x08\
    \x1c\nL\n\x04\x04\x03\x02\0\x12\x04\xca\x01\x02\x1f\x1a>\x20Metadata\x20\
    for\x20the\x20policies\x20that\x20are\x20attached\x20to\x20the\x20resour\
    ce.\n\n\r\n\x05\x04\x03\x02\0\x04\x12\x04\xca\x01\x02\n\n\r\n\x05\x04\
    \x03\x02\0\x06\x12\x04\xca\x01\x0b\x11\n\r\n\x05\x04\x03\x02\0\x01\x12\
    \x04\xca\x01\x12\x1a\n\r\n\x05\x04\x03\x02\0\x03\x12\x04\xca\x01\x1d\x1e\
    \n\xc1\x01\n\x04\x04\x03\x02\x01\x12\x04\xce\x01\x02\x1d\x1a\xb2\x01\x20\
    A\x20page\x20token\x20that\x20you\x20can\x20use\x20in\x20a\x20[ListPolic\
    iesRequest][google.iam.v2.ListPoliciesRequest]\x20to\x20retrieve\x20the\
    \n\x20next\x20page.\x20If\x20this\x20field\x20is\x20omitted,\x20there\
    \x20are\x20no\x20additional\x20pages.\n\n\r\n\x05\x04\x03\x02\x01\x05\
    \x12\x04\xce\x01\x02\x08\n\r\n\x05\x04\x03\x02\x01\x01\x12\x04\xce\x01\t\
    \x18\n\r\n\x05\x04\x03\x02\x01\x03\x12\x04\xce\x01\x1b\x1c\n0\n\x02\x04\
    \x04\x12\x06\xd2\x01\0\xde\x01\x01\x1a\"\x20Request\x20message\x20for\
    \x20`GetPolicy`.\n\n\x0b\n\x03\x04\x04\x01\x12\x04\xd2\x01\x08\x18\n\xfb\
    \x03\n\x04\x04\x04\x02\0\x12\x04\xdd\x01\x02;\x1a\xec\x03\x20Required.\
    \x20The\x20resource\x20name\x20of\x20the\x20policy\x20to\x20retrieve.\
    \x20Format:\n\x20`policies/{attachment_point}/denypolicies/{policy_id}`\
    \n\n\n\x20Use\x20the\x20URL-encoded\x20full\x20resource\x20name,\x20whic\
    h\x20means\x20that\x20the\x20forward-slash\n\x20character,\x20`/`,\x20mu\
    st\x20be\x20written\x20as\x20`%2F`.\x20For\x20example,\n\x20`policies/cl\
    oudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/m\
    y-policy`.\n\n\x20For\x20organizations\x20and\x20folders,\x20use\x20the\
    \x20numeric\x20ID\x20in\x20the\x20full\x20resource\n\x20name.\x20For\x20\
    projects,\x20you\x20can\x20use\x20the\x20alphanumeric\x20or\x20the\x20nu\
    meric\x20ID.\n\n\r\n\x05\x04\x04\x02\0\x05\x12\x04\xdd\x01\x02\x08\n\r\n\
    \x05\x04\x04\x02\0\x01\x12\x04\xdd\x01\t\r\n\r\n\x05\x04\x04\x02\0\x03\
    \x12\x04\xdd\x01\x10\x11\n\r\n\x05\x04\x04\x02\0\x08\x12\x04\xdd\x01\x12\
    :\n\x10\n\x08\x04\x04\x02\0\x08\x9c\x08\0\x12\x04\xdd\x01\x139\n3\n\x02\
    \x04\x05\x12\x06\xe1\x01\0\xf7\x01\x01\x1a%\x20Request\x20message\x20for\
    \x20`CreatePolicy`.\n\n\x0b\n\x03\x04\x05\x01\x12\x04\xe1\x01\x08\x1b\n\
    \xb1\x04\n\x04\x04\x05\x02\0\x12\x04\xed\x01\x02=\x1a\xa2\x04\x20Require\
    d.\x20The\x20resource\x20that\x20the\x20policy\x20is\x20attached\x20to,\
    \x20along\x20with\x20the\x20kind\x20of\x20policy\n\x20to\x20create.\x20F\
    ormat:\x20`policies/{attachment_point}/denypolicies`\n\n\n\x20The\x20att\
    achment\x20point\x20is\x20identified\x20by\x20its\x20URL-encoded\x20full\
    \x20resource\x20name,\n\x20which\x20means\x20that\x20the\x20forward-slas\
    h\x20character,\x20`/`,\x20must\x20be\x20written\x20as\n\x20`%2F`.\x20Fo\
    r\x20example,\n\x20`policies/cloudresourcemanager.googleapis.com%2Fproje\
    cts%2Fmy-project/denypolicies`.\n\n\x20For\x20organizations\x20and\x20fo\
    lders,\x20use\x20the\x20numeric\x20ID\x20in\x20the\x20full\x20resource\n\
    \x20name.\x20For\x20projects,\x20you\x20can\x20use\x20the\x20alphanumeri\
    c\x20or\x20the\x20numeric\x20ID.\n\n\r\n\x05\x04\x05\x02\0\x05\x12\x04\
    \xed\x01\x02\x08\n\r\n\x05\x04\x05\x02\0\x01\x12\x04\xed\x01\t\x0f\n\r\n\
    \x05\x04\x05\x02\0\x03\x12\x04\xed\x01\x12\x13\n\r\n\x05\x04\x05\x02\0\
    \x08\x12\x04\xed\x01\x14<\n\x10\n\x08\x04\x05\x02\0\x08\x9c\x08\0\x12\
    \x04\xed\x01\x15;\n/\n\x04\x04\x05\x02\x01\x12\x04\xf0\x01\x02=\x1a!\x20\
    Required.\x20The\x20policy\x20to\x20create.\n\n\r\n\x05\x04\x05\x02\x01\
    \x06\x12\x04\xf0\x01\x02\x08\n\r\n\x05\x04\x05\x02\x01\x01\x12\x04\xf0\
    \x01\t\x0f\n\r\n\x05\x04\x05\x02\x01\x03\x12\x04\xf0\x01\x12\x13\n\r\n\
    \x05\x04\x05\x02\x01\x08\x12\x04\xf0\x01\x14<\n\x10\n\x08\x04\x05\x02\
    \x01\x08\x9c\x08\0\x12\x04\xf0\x01\x15;\n\xa8\x02\n\x04\x04\x05\x02\x02\
    \x12\x04\xf6\x01\x02\x17\x1a\x99\x02\x20The\x20ID\x20to\x20use\x20for\
    \x20this\x20policy,\x20which\x20will\x20become\x20the\x20final\x20compon\
    ent\x20of\n\x20the\x20policy's\x20resource\x20name.\x20The\x20ID\x20must\
    \x20contain\x203\x20to\x2063\x20characters.\x20It\x20can\n\x20contain\
    \x20lowercase\x20letters\x20and\x20numbers,\x20as\x20well\x20as\x20dashe\
    s\x20(`-`)\x20and\x20periods\n\x20(`.`).\x20The\x20first\x20character\
    \x20must\x20be\x20a\x20lowercase\x20letter.\n\n\r\n\x05\x04\x05\x02\x02\
    \x05\x12\x04\xf6\x01\x02\x08\n\r\n\x05\x04\x05\x02\x02\x01\x12\x04\xf6\
    \x01\t\x12\n\r\n\x05\x04\x05\x02\x02\x03\x12\x04\xf6\x01\x15\x16\n3\n\
    \x02\x04\x06\x12\x06\xfa\x01\0\x81\x02\x01\x1a%\x20Request\x20message\
    \x20for\x20`UpdatePolicy`.\n\n\x0b\n\x03\x04\x06\x01\x12\x04\xfa\x01\x08\
    \x1b\n\xf4\x01\n\x04\x04\x06\x02\0\x12\x04\x80\x02\x02=\x1a\xe5\x01\x20R\
    equired.\x20The\x20policy\x20to\x20update.\n\n\x20To\x20prevent\x20confl\
    icting\x20updates,\x20the\x20`etag`\x20value\x20must\x20match\x20the\x20\
    value\x20that\n\x20is\x20stored\x20in\x20IAM.\x20If\x20the\x20`etag`\x20\
    values\x20do\x20not\x20match,\x20the\x20request\x20fails\x20with\n\x20a\
    \x20`409`\x20error\x20code\x20and\x20`ABORTED`\x20status.\n\n\r\n\x05\
    \x04\x06\x02\0\x06\x12\x04\x80\x02\x02\x08\n\r\n\x05\x04\x06\x02\0\x01\
    \x12\x04\x80\x02\t\x0f\n\r\n\x05\x04\x06\x02\0\x03\x12\x04\x80\x02\x12\
    \x13\n\r\n\x05\x04\x06\x02\0\x08\x12\x04\x80\x02\x14<\n\x10\n\x08\x04\
    \x06\x02\0\x08\x9c\x08\0\x12\x04\x80\x02\x15;\n3\n\x02\x04\x07\x12\x06\
    \x84\x02\0\x98\x02\x01\x1a%\x20Request\x20message\x20for\x20`DeletePolic\
    y`.\n\n\x0b\n\x03\x04\x07\x01\x12\x04\x84\x02\x08\x1b\n\xf9\x03\n\x04\
    \x04\x07\x02\0\x12\x04\x8f\x02\x02;\x1a\xea\x03\x20Required.\x20The\x20r\
    esource\x20name\x20of\x20the\x20policy\x20to\x20delete.\x20Format:\n\x20\
    `policies/{attachment_point}/denypolicies/{policy_id}`\n\n\n\x20Use\x20t\
    he\x20URL-encoded\x20full\x20resource\x20name,\x20which\x20means\x20that\
    \x20the\x20forward-slash\n\x20character,\x20`/`,\x20must\x20be\x20writte\
    n\x20as\x20`%2F`.\x20For\x20example,\n\x20`policies/cloudresourcemanager\
    .googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-policy`.\n\n\x20\
    For\x20organizations\x20and\x20folders,\x20use\x20the\x20numeric\x20ID\
    \x20in\x20the\x20full\x20resource\n\x20name.\x20For\x20projects,\x20you\
    \x20can\x20use\x20the\x20alphanumeric\x20or\x20the\x20numeric\x20ID.\n\n\
    \r\n\x05\x04\x07\x02\0\x05\x12\x04\x8f\x02\x02\x08\n\r\n\x05\x04\x07\x02\
    \0\x01\x12\x04\x8f\x02\t\r\n\r\n\x05\x04\x07\x02\0\x03\x12\x04\x8f\x02\
    \x10\x11\n\r\n\x05\x04\x07\x02\0\x08\x12\x04\x8f\x02\x12:\n\x10\n\x08\
    \x04\x07\x02\0\x08\x9c\x08\0\x12\x04\x8f\x02\x139\n\x99\x02\n\x04\x04\
    \x07\x02\x01\x12\x04\x97\x02\x02;\x1a\x8a\x02\x20Optional.\x20The\x20exp\
    ected\x20`etag`\x20of\x20the\x20policy\x20to\x20delete.\x20If\x20the\x20\
    value\x20does\x20not\x20match\n\x20the\x20value\x20that\x20is\x20stored\
    \x20in\x20IAM,\x20the\x20request\x20fails\x20with\x20a\x20`409`\x20error\
    \x20code\n\x20and\x20`ABORTED`\x20status.\n\n\x20If\x20you\x20omit\x20th\
    is\x20field,\x20the\x20policy\x20is\x20deleted\x20regardless\x20of\x20it\
    s\x20current\n\x20`etag`.\n\n\r\n\x05\x04\x07\x02\x01\x05\x12\x04\x97\
    \x02\x02\x08\n\r\n\x05\x04\x07\x02\x01\x01\x12\x04\x97\x02\t\r\n\r\n\x05\
    \x04\x07\x02\x01\x03\x12\x04\x97\x02\x10\x11\n\r\n\x05\x04\x07\x02\x01\
    \x08\x12\x04\x97\x02\x12:\n\x10\n\x08\x04\x07\x02\x01\x08\x9c\x08\0\x12\
    \x04\x97\x02\x139\n>\n\x02\x04\x08\x12\x06\x9b\x02\0\x9e\x02\x01\x1a0\
    \x20Metadata\x20for\x20long-running\x20`Policy`\x20operations.\n\n\x0b\n\
    \x03\x04\x08\x01\x12\x04\x9b\x02\x08\x1f\nN\n\x04\x04\x08\x02\0\x12\x04\
    \x9d\x02\x02,\x1a@\x20Timestamp\x20when\x20the\x20`google.longrunning.Op\
    eration`\x20was\x20created.\n\n\r\n\x05\x04\x08\x02\0\x06\x12\x04\x9d\
    \x02\x02\x1b\n\r\n\x05\x04\x08\x02\0\x01\x12\x04\x9d\x02\x1c'\n\r\n\x05\
    \x04\x08\x02\0\x03\x12\x04\x9d\x02*+b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(6);
            deps.push(super::annotations::file_descriptor().clone());
            deps.push(super::client::file_descriptor().clone());
            deps.push(super::field_behavior::file_descriptor().clone());
            deps.push(super::deny::file_descriptor().clone());
            deps.push(super::operations::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(9);
            messages.push(Policy::generated_message_descriptor_data());
            messages.push(PolicyRule::generated_message_descriptor_data());
            messages.push(ListPoliciesRequest::generated_message_descriptor_data());
            messages.push(ListPoliciesResponse::generated_message_descriptor_data());
            messages.push(GetPolicyRequest::generated_message_descriptor_data());
            messages.push(CreatePolicyRequest::generated_message_descriptor_data());
            messages.push(UpdatePolicyRequest::generated_message_descriptor_data());
            messages.push(DeletePolicyRequest::generated_message_descriptor_data());
            messages.push(PolicyOperationMetadata::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
