// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]


#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `google/cloud/securitycenter/v1/backup_disaster_recovery.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

///  Information related to Google Cloud Backup and DR Service findings.
// @@protoc_insertion_point(message:google.cloud.securitycenter.v1.BackupDisasterRecovery)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct BackupDisasterRecovery {
    // message fields
    ///  The name of a Backup and DR template which comprises one or more backup
    ///  policies. See the [Backup and DR
    ///  documentation](https://cloud.google.com/backup-disaster-recovery/docs/concepts/backup-plan#temp)
    ///  for more information. For example, `snap-ov`.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.BackupDisasterRecovery.backup_template)
    pub backup_template: ::std::string::String,
    ///  The names of Backup and DR policies that are associated with a template
    ///  and that define when to run a backup, how frequently to run a backup, and
    ///  how long to retain the backup image. For example, `onvaults`.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.BackupDisasterRecovery.policies)
    pub policies: ::std::vec::Vec<::std::string::String>,
    ///  The name of a Backup and DR host, which is managed by the backup and
    ///  recovery appliance and known to the management console. The host can be of
    ///  type Generic (for example, Compute Engine, SQL Server, Oracle DB, SMB file
    ///  system, etc.), vCenter, or an ESX server. See the [Backup and DR
    ///  documentation on
    ///  hosts](https://cloud.google.com/backup-disaster-recovery/docs/configuration/manage-hosts-and-their-applications)
    ///  for more information. For example, `centos7-01`.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.BackupDisasterRecovery.host)
    pub host: ::std::string::String,
    ///  The names of Backup and DR applications. An application is a VM, database,
    ///  or file system on a managed host monitored by a backup and recovery
    ///  appliance. For example, `centos7-01-vol00`, `centos7-01-vol01`,
    ///  `centos7-01-vol02`.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.BackupDisasterRecovery.applications)
    pub applications: ::std::vec::Vec<::std::string::String>,
    ///  The name of the Backup and DR storage pool that the backup and recovery
    ///  appliance is storing data in. The storage pool could be of type Cloud,
    ///  Primary, Snapshot, or OnVault. See the [Backup and DR documentation on
    ///  storage
    ///  pools](https://cloud.google.com/backup-disaster-recovery/docs/concepts/storage-pools).
    ///  For example, `DiskPoolOne`.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.BackupDisasterRecovery.storage_pool)
    pub storage_pool: ::std::string::String,
    ///  The names of Backup and DR advanced policy options of a policy applying to
    ///  an application. See the [Backup and DR documentation on policy
    ///  options](https://cloud.google.com/backup-disaster-recovery/docs/create-plan/policy-settings).
    ///  For example, `skipofflineappsincongrp, nounmap`.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.BackupDisasterRecovery.policy_options)
    pub policy_options: ::std::vec::Vec<::std::string::String>,
    ///  The name of the Backup and DR resource profile that specifies the storage
    ///  media for backups of application and VM data. See the [Backup and DR
    ///  documentation on
    ///  profiles](https://cloud.google.com/backup-disaster-recovery/docs/concepts/backup-plan#profile).
    ///  For example, `GCP`.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.BackupDisasterRecovery.profile)
    pub profile: ::std::string::String,
    ///  The name of the Backup and DR appliance that captures, moves, and manages
    ///  the lifecycle of backup data. For example, `backup-server-57137`.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.BackupDisasterRecovery.appliance)
    pub appliance: ::std::string::String,
    ///  The backup type of the Backup and DR image.
    ///  For example, `Snapshot`, `Remote Snapshot`, `OnVault`.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.BackupDisasterRecovery.backup_type)
    pub backup_type: ::std::string::String,
    ///  The timestamp at which the Backup and DR backup was created.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.BackupDisasterRecovery.backup_create_time)
    pub backup_create_time: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // special fields
    // @@protoc_insertion_point(special_field:google.cloud.securitycenter.v1.BackupDisasterRecovery.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a BackupDisasterRecovery {
    fn default() -> &'a BackupDisasterRecovery {
        <BackupDisasterRecovery as ::protobuf::Message>::default_instance()
    }
}

impl BackupDisasterRecovery {
    pub fn new() -> BackupDisasterRecovery {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(10);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "backup_template",
            |m: &BackupDisasterRecovery| { &m.backup_template },
            |m: &mut BackupDisasterRecovery| { &mut m.backup_template },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "policies",
            |m: &BackupDisasterRecovery| { &m.policies },
            |m: &mut BackupDisasterRecovery| { &mut m.policies },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "host",
            |m: &BackupDisasterRecovery| { &m.host },
            |m: &mut BackupDisasterRecovery| { &mut m.host },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "applications",
            |m: &BackupDisasterRecovery| { &m.applications },
            |m: &mut BackupDisasterRecovery| { &mut m.applications },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "storage_pool",
            |m: &BackupDisasterRecovery| { &m.storage_pool },
            |m: &mut BackupDisasterRecovery| { &mut m.storage_pool },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "policy_options",
            |m: &BackupDisasterRecovery| { &m.policy_options },
            |m: &mut BackupDisasterRecovery| { &mut m.policy_options },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "profile",
            |m: &BackupDisasterRecovery| { &m.profile },
            |m: &mut BackupDisasterRecovery| { &mut m.profile },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "appliance",
            |m: &BackupDisasterRecovery| { &m.appliance },
            |m: &mut BackupDisasterRecovery| { &mut m.appliance },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "backup_type",
            |m: &BackupDisasterRecovery| { &m.backup_type },
            |m: &mut BackupDisasterRecovery| { &mut m.backup_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "backup_create_time",
            |m: &BackupDisasterRecovery| { &m.backup_create_time },
            |m: &mut BackupDisasterRecovery| { &mut m.backup_create_time },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<BackupDisasterRecovery>(
            "BackupDisasterRecovery",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for BackupDisasterRecovery {
    const NAME: &'static str = "BackupDisasterRecovery";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.backup_template = is.read_string()?;
                },
                18 => {
                    self.policies.push(is.read_string()?);
                },
                26 => {
                    self.host = is.read_string()?;
                },
                34 => {
                    self.applications.push(is.read_string()?);
                },
                42 => {
                    self.storage_pool = is.read_string()?;
                },
                50 => {
                    self.policy_options.push(is.read_string()?);
                },
                58 => {
                    self.profile = is.read_string()?;
                },
                66 => {
                    self.appliance = is.read_string()?;
                },
                74 => {
                    self.backup_type = is.read_string()?;
                },
                82 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.backup_create_time)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.backup_template.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.backup_template);
        }
        for value in &self.policies {
            my_size += ::protobuf::rt::string_size(2, &value);
        };
        if !self.host.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.host);
        }
        for value in &self.applications {
            my_size += ::protobuf::rt::string_size(4, &value);
        };
        if !self.storage_pool.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.storage_pool);
        }
        for value in &self.policy_options {
            my_size += ::protobuf::rt::string_size(6, &value);
        };
        if !self.profile.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.profile);
        }
        if !self.appliance.is_empty() {
            my_size += ::protobuf::rt::string_size(8, &self.appliance);
        }
        if !self.backup_type.is_empty() {
            my_size += ::protobuf::rt::string_size(9, &self.backup_type);
        }
        if let Some(v) = self.backup_create_time.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.backup_template.is_empty() {
            os.write_string(1, &self.backup_template)?;
        }
        for v in &self.policies {
            os.write_string(2, &v)?;
        };
        if !self.host.is_empty() {
            os.write_string(3, &self.host)?;
        }
        for v in &self.applications {
            os.write_string(4, &v)?;
        };
        if !self.storage_pool.is_empty() {
            os.write_string(5, &self.storage_pool)?;
        }
        for v in &self.policy_options {
            os.write_string(6, &v)?;
        };
        if !self.profile.is_empty() {
            os.write_string(7, &self.profile)?;
        }
        if !self.appliance.is_empty() {
            os.write_string(8, &self.appliance)?;
        }
        if !self.backup_type.is_empty() {
            os.write_string(9, &self.backup_type)?;
        }
        if let Some(v) = self.backup_create_time.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(10, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> BackupDisasterRecovery {
        BackupDisasterRecovery::new()
    }

    fn clear(&mut self) {
        self.backup_template.clear();
        self.policies.clear();
        self.host.clear();
        self.applications.clear();
        self.storage_pool.clear();
        self.policy_options.clear();
        self.profile.clear();
        self.appliance.clear();
        self.backup_type.clear();
        self.backup_create_time.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static BackupDisasterRecovery {
        static instance: BackupDisasterRecovery = BackupDisasterRecovery {
            backup_template: ::std::string::String::new(),
            policies: ::std::vec::Vec::new(),
            host: ::std::string::String::new(),
            applications: ::std::vec::Vec::new(),
            storage_pool: ::std::string::String::new(),
            policy_options: ::std::vec::Vec::new(),
            profile: ::std::string::String::new(),
            appliance: ::std::string::String::new(),
            backup_type: ::std::string::String::new(),
            backup_create_time: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for BackupDisasterRecovery {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("BackupDisasterRecovery").unwrap()).clone()
    }
}

impl ::std::fmt::Display for BackupDisasterRecovery {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BackupDisasterRecovery {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n=google/cloud/securitycenter/v1/backup_disaster_recovery.proto\x12\x1e\
    google.cloud.securitycenter.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\
    \x82\x03\n\x16BackupDisasterRecovery\x12'\n\x0fbackup_template\x18\x01\
    \x20\x01(\tR\x0ebackupTemplate\x12\x1a\n\x08policies\x18\x02\x20\x03(\tR\
    \x08policies\x12\x12\n\x04host\x18\x03\x20\x01(\tR\x04host\x12\"\n\x0cap\
    plications\x18\x04\x20\x03(\tR\x0capplications\x12!\n\x0cstorage_pool\
    \x18\x05\x20\x01(\tR\x0bstoragePool\x12%\n\x0epolicy_options\x18\x06\x20\
    \x03(\tR\rpolicyOptions\x12\x18\n\x07profile\x18\x07\x20\x01(\tR\x07prof\
    ile\x12\x1c\n\tappliance\x18\x08\x20\x01(\tR\tappliance\x12\x1f\n\x0bbac\
    kup_type\x18\t\x20\x01(\tR\nbackupType\x12H\n\x12backup_create_time\x18\
    \n\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\x10backupCreateTimeB\xf5\
    \x01\n\"com.google.cloud.securitycenter.v1B\x1bBackupDisasterRecoveryPro\
    toP\x01ZJcloud.google.com/go/securitycenter/apiv1/securitycenterpb;secur\
    itycenterpb\xaa\x02\x1eGoogle.Cloud.SecurityCenter.V1\xca\x02\x1eGoogle\
    \\Cloud\\SecurityCenter\\V1\xea\x02!Google::Cloud::SecurityCenter::V1J\
    \x8c\x1e\n\x06\x12\x04\x0e\0W\x01\n\xbc\x04\n\x01\x0c\x12\x03\x0e\0\x122\
    \xb1\x04\x20Copyright\x202024\x20Google\x20LLC\n\n\x20Licensed\x20under\
    \x20the\x20Apache\x20License,\x20Version\x202.0\x20(the\x20\"License\");\
    \n\x20you\x20may\x20not\x20use\x20this\x20file\x20except\x20in\x20compli\
    ance\x20with\x20the\x20License.\n\x20You\x20may\x20obtain\x20a\x20copy\
    \x20of\x20the\x20License\x20at\n\n\x20\x20\x20\x20\x20http://www.apache.\
    org/licenses/LICENSE-2.0\n\n\x20Unless\x20required\x20by\x20applicable\
    \x20law\x20or\x20agreed\x20to\x20in\x20writing,\x20software\n\x20distrib\
    uted\x20under\x20the\x20License\x20is\x20distributed\x20on\x20an\x20\"AS\
    \x20IS\"\x20BASIS,\n\x20WITHOUT\x20WARRANTIES\x20OR\x20CONDITIONS\x20OF\
    \x20ANY\x20KIND,\x20either\x20express\x20or\x20implied.\n\x20See\x20the\
    \x20License\x20for\x20the\x20specific\x20language\x20governing\x20permis\
    sions\x20and\n\x20limitations\x20under\x20the\x20License.\n\n\x08\n\x01\
    \x02\x12\x03\x10\0'\n\t\n\x02\x03\0\x12\x03\x12\0)\n\x08\n\x01\x08\x12\
    \x03\x14\0;\n\t\n\x02\x08%\x12\x03\x14\0;\n\x08\n\x01\x08\x12\x03\x15\0a\
    \n\t\n\x02\x08\x0b\x12\x03\x15\0a\n\x08\n\x01\x08\x12\x03\x16\0\"\n\t\n\
    \x02\x08\n\x12\x03\x16\0\"\n\x08\n\x01\x08\x12\x03\x17\0<\n\t\n\x02\x08\
    \x08\x12\x03\x17\0<\n\x08\n\x01\x08\x12\x03\x18\0;\n\t\n\x02\x08\x01\x12\
    \x03\x18\0;\n\x08\n\x01\x08\x12\x03\x19\0;\n\t\n\x02\x08)\x12\x03\x19\0;\
    \n\x08\n\x01\x08\x12\x03\x1a\0:\n\t\n\x02\x08-\x12\x03\x1a\0:\nQ\n\x02\
    \x04\0\x12\x04\x1d\0W\x01\x1aE\x20Information\x20related\x20to\x20Google\
    \x20Cloud\x20Backup\x20and\x20DR\x20Service\x20findings.\n\n\n\n\x03\x04\
    \0\x01\x12\x03\x1d\x08\x1e\n\x8a\x02\n\x04\x04\0\x02\0\x12\x03\"\x02\x1d\
    \x1a\xfc\x01\x20The\x20name\x20of\x20a\x20Backup\x20and\x20DR\x20templat\
    e\x20which\x20comprises\x20one\x20or\x20more\x20backup\n\x20policies.\
    \x20See\x20the\x20[Backup\x20and\x20DR\n\x20documentation](https://cloud\
    .google.com/backup-disaster-recovery/docs/concepts/backup-plan#temp)\n\
    \x20for\x20more\x20information.\x20For\x20example,\x20`snap-ov`.\n\n\x0c\
    \n\x05\x04\0\x02\0\x05\x12\x03\"\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\
    \x03\"\t\x18\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\"\x1b\x1c\n\xe1\x01\n\
    \x04\x04\0\x02\x01\x12\x03'\x02\x1f\x1a\xd3\x01\x20The\x20names\x20of\
    \x20Backup\x20and\x20DR\x20policies\x20that\x20are\x20associated\x20with\
    \x20a\x20template\n\x20and\x20that\x20define\x20when\x20to\x20run\x20a\
    \x20backup,\x20how\x20frequently\x20to\x20run\x20a\x20backup,\x20and\n\
    \x20how\x20long\x20to\x20retain\x20the\x20backup\x20image.\x20For\x20exa\
    mple,\x20`onvaults`.\n\n\x0c\n\x05\x04\0\x02\x01\x04\x12\x03'\x02\n\n\
    \x0c\n\x05\x04\0\x02\x01\x05\x12\x03'\x0b\x11\n\x0c\n\x05\x04\0\x02\x01\
    \x01\x12\x03'\x12\x1a\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03'\x1d\x1e\n\
    \xe4\x03\n\x04\x04\0\x02\x02\x12\x030\x02\x12\x1a\xd6\x03\x20The\x20name\
    \x20of\x20a\x20Backup\x20and\x20DR\x20host,\x20which\x20is\x20managed\
    \x20by\x20the\x20backup\x20and\n\x20recovery\x20appliance\x20and\x20know\
    n\x20to\x20the\x20management\x20console.\x20The\x20host\x20can\x20be\x20\
    of\n\x20type\x20Generic\x20(for\x20example,\x20Compute\x20Engine,\x20SQL\
    \x20Server,\x20Oracle\x20DB,\x20SMB\x20file\n\x20system,\x20etc.),\x20vC\
    enter,\x20or\x20an\x20ESX\x20server.\x20See\x20the\x20[Backup\x20and\x20\
    DR\n\x20documentation\x20on\n\x20hosts](https://cloud.google.com/backup-\
    disaster-recovery/docs/configuration/manage-hosts-and-their-applications\
    )\n\x20for\x20more\x20information.\x20For\x20example,\x20`centos7-01`.\n\
    \n\x0c\n\x05\x04\0\x02\x02\x05\x12\x030\x02\x08\n\x0c\n\x05\x04\0\x02\
    \x02\x01\x12\x030\t\r\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x030\x10\x11\n\
    \xf5\x01\n\x04\x04\0\x02\x03\x12\x036\x02#\x1a\xe7\x01\x20The\x20names\
    \x20of\x20Backup\x20and\x20DR\x20applications.\x20An\x20application\x20i\
    s\x20a\x20VM,\x20database,\n\x20or\x20file\x20system\x20on\x20a\x20manag\
    ed\x20host\x20monitored\x20by\x20a\x20backup\x20and\x20recovery\n\x20app\
    liance.\x20For\x20example,\x20`centos7-01-vol00`,\x20`centos7-01-vol01`,\
    \n\x20`centos7-01-vol02`.\n\n\x0c\n\x05\x04\0\x02\x03\x04\x12\x036\x02\n\
    \n\x0c\n\x05\x04\0\x02\x03\x05\x12\x036\x0b\x11\n\x0c\n\x05\x04\0\x02\
    \x03\x01\x12\x036\x12\x1e\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x036!\"\n\
    \xe5\x02\n\x04\x04\0\x02\x04\x12\x03>\x02\x1a\x1a\xd7\x02\x20The\x20name\
    \x20of\x20the\x20Backup\x20and\x20DR\x20storage\x20pool\x20that\x20the\
    \x20backup\x20and\x20recovery\n\x20appliance\x20is\x20storing\x20data\
    \x20in.\x20The\x20storage\x20pool\x20could\x20be\x20of\x20type\x20Cloud,\
    \n\x20Primary,\x20Snapshot,\x20or\x20OnVault.\x20See\x20the\x20[Backup\
    \x20and\x20DR\x20documentation\x20on\n\x20storage\n\x20pools](https://cl\
    oud.google.com/backup-disaster-recovery/docs/concepts/storage-pools).\n\
    \x20For\x20example,\x20`DiskPoolOne`.\n\n\x0c\n\x05\x04\0\x02\x04\x05\
    \x12\x03>\x02\x08\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03>\t\x15\n\x0c\n\
    \x05\x04\0\x02\x04\x03\x12\x03>\x18\x19\n\xab\x02\n\x04\x04\0\x02\x05\
    \x12\x03D\x02%\x1a\x9d\x02\x20The\x20names\x20of\x20Backup\x20and\x20DR\
    \x20advanced\x20policy\x20options\x20of\x20a\x20policy\x20applying\x20to\
    \n\x20an\x20application.\x20See\x20the\x20[Backup\x20and\x20DR\x20docume\
    ntation\x20on\x20policy\n\x20options](https://cloud.google.com/backup-di\
    saster-recovery/docs/create-plan/policy-settings).\n\x20For\x20example,\
    \x20`skipofflineappsincongrp,\x20nounmap`.\n\n\x0c\n\x05\x04\0\x02\x05\
    \x04\x12\x03D\x02\n\n\x0c\n\x05\x04\0\x02\x05\x05\x12\x03D\x0b\x11\n\x0c\
    \n\x05\x04\0\x02\x05\x01\x12\x03D\x12\x20\n\x0c\n\x05\x04\0\x02\x05\x03\
    \x12\x03D#$\n\xa7\x02\n\x04\x04\0\x02\x06\x12\x03K\x02\x15\x1a\x99\x02\
    \x20The\x20name\x20of\x20the\x20Backup\x20and\x20DR\x20resource\x20profi\
    le\x20that\x20specifies\x20the\x20storage\n\x20media\x20for\x20backups\
    \x20of\x20application\x20and\x20VM\x20data.\x20See\x20the\x20[Backup\x20\
    and\x20DR\n\x20documentation\x20on\n\x20profiles](https://cloud.google.c\
    om/backup-disaster-recovery/docs/concepts/backup-plan#profile).\n\x20For\
    \x20example,\x20`GCP`.\n\n\x0c\n\x05\x04\0\x02\x06\x05\x12\x03K\x02\x08\
    \n\x0c\n\x05\x04\0\x02\x06\x01\x12\x03K\t\x10\n\x0c\n\x05\x04\0\x02\x06\
    \x03\x12\x03K\x13\x14\n\x9c\x01\n\x04\x04\0\x02\x07\x12\x03O\x02\x17\x1a\
    \x8e\x01\x20The\x20name\x20of\x20the\x20Backup\x20and\x20DR\x20appliance\
    \x20that\x20captures,\x20moves,\x20and\x20manages\n\x20the\x20lifecycle\
    \x20of\x20backup\x20data.\x20For\x20example,\x20`backup-server-57137`.\n\
    \n\x0c\n\x05\x04\0\x02\x07\x05\x12\x03O\x02\x08\n\x0c\n\x05\x04\0\x02\
    \x07\x01\x12\x03O\t\x12\n\x0c\n\x05\x04\0\x02\x07\x03\x12\x03O\x15\x16\n\
    r\n\x04\x04\0\x02\x08\x12\x03S\x02\x19\x1ae\x20The\x20backup\x20type\x20\
    of\x20the\x20Backup\x20and\x20DR\x20image.\n\x20For\x20example,\x20`Snap\
    shot`,\x20`Remote\x20Snapshot`,\x20`OnVault`.\n\n\x0c\n\x05\x04\0\x02\
    \x08\x05\x12\x03S\x02\x08\n\x0c\n\x05\x04\0\x02\x08\x01\x12\x03S\t\x14\n\
    \x0c\n\x05\x04\0\x02\x08\x03\x12\x03S\x17\x18\nK\n\x04\x04\0\x02\t\x12\
    \x03V\x024\x1a>\x20The\x20timestamp\x20at\x20which\x20the\x20Backup\x20a\
    nd\x20DR\x20backup\x20was\x20created.\n\n\x0c\n\x05\x04\0\x02\t\x06\x12\
    \x03V\x02\x1b\n\x0c\n\x05\x04\0\x02\t\x01\x12\x03V\x1c.\n\x0c\n\x05\x04\
    \0\x02\t\x03\x12\x03V13b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(BackupDisasterRecovery::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
