// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]


#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `google/cloud/securitycenter/v1/container.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

///  Container associated with the finding.
// @@protoc_insertion_point(message:google.cloud.securitycenter.v1.Container)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Container {
    // message fields
    ///  Name of the container.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.Container.name)
    pub name: ::std::string::String,
    ///  Container image URI provided when configuring a pod or container. This
    ///  string can identify a container image version using mutable tags.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.Container.uri)
    pub uri: ::std::string::String,
    ///  Optional container image ID, if provided by the container runtime. Uniquely
    ///  identifies the container image launched using a container image digest.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.Container.image_id)
    pub image_id: ::std::string::String,
    ///  Container labels, as provided by the container runtime.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.Container.labels)
    pub labels: ::std::vec::Vec<super::label::Label>,
    ///  The time that the container was created.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v1.Container.create_time)
    pub create_time: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // special fields
    // @@protoc_insertion_point(special_field:google.cloud.securitycenter.v1.Container.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Container {
    fn default() -> &'a Container {
        <Container as ::protobuf::Message>::default_instance()
    }
}

impl Container {
    pub fn new() -> Container {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &Container| { &m.name },
            |m: &mut Container| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "uri",
            |m: &Container| { &m.uri },
            |m: &mut Container| { &mut m.uri },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "image_id",
            |m: &Container| { &m.image_id },
            |m: &mut Container| { &mut m.image_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "labels",
            |m: &Container| { &m.labels },
            |m: &mut Container| { &mut m.labels },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "create_time",
            |m: &Container| { &m.create_time },
            |m: &mut Container| { &mut m.create_time },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Container>(
            "Container",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Container {
    const NAME: &'static str = "Container";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                18 => {
                    self.uri = is.read_string()?;
                },
                26 => {
                    self.image_id = is.read_string()?;
                },
                34 => {
                    self.labels.push(is.read_message()?);
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.create_time)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if !self.uri.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.uri);
        }
        if !self.image_id.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.image_id);
        }
        for value in &self.labels {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.create_time.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if !self.uri.is_empty() {
            os.write_string(2, &self.uri)?;
        }
        if !self.image_id.is_empty() {
            os.write_string(3, &self.image_id)?;
        }
        for v in &self.labels {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        };
        if let Some(v) = self.create_time.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Container {
        Container::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.uri.clear();
        self.image_id.clear();
        self.labels.clear();
        self.create_time.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Container {
        static instance: Container = Container {
            name: ::std::string::String::new(),
            uri: ::std::string::String::new(),
            image_id: ::std::string::String::new(),
            labels: ::std::vec::Vec::new(),
            create_time: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Container {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Container").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Container {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Container {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n.google/cloud/securitycenter/v1/container.proto\x12\x1egoogle.cloud.se\
    curitycenter.v1\x1a*google/cloud/securitycenter/v1/label.proto\x1a\x1fgo\
    ogle/protobuf/timestamp.proto\"\xc8\x01\n\tContainer\x12\x12\n\x04name\
    \x18\x01\x20\x01(\tR\x04name\x12\x10\n\x03uri\x18\x02\x20\x01(\tR\x03uri\
    \x12\x19\n\x08image_id\x18\x03\x20\x01(\tR\x07imageId\x12=\n\x06labels\
    \x18\x04\x20\x03(\x0b2%.google.cloud.securitycenter.v1.LabelR\x06labels\
    \x12;\n\x0bcreate_time\x18\x05\x20\x01(\x0b2\x1a.google.protobuf.Timesta\
    mpR\ncreateTimeB\xe8\x01\n\"com.google.cloud.securitycenter.v1B\x0eConta\
    inerProtoP\x01ZJcloud.google.com/go/securitycenter/apiv1/securitycenterp\
    b;securitycenterpb\xaa\x02\x1eGoogle.Cloud.SecurityCenter.V1\xca\x02\x1e\
    Google\\Cloud\\SecurityCenter\\V1\xea\x02!Google::Cloud::SecurityCenter:\
    :V1J\x87\x0c\n\x06\x12\x04\x0e\0/\x01\n\xbc\x04\n\x01\x0c\x12\x03\x0e\0\
    \x122\xb1\x04\x20Copyright\x202024\x20Google\x20LLC\n\n\x20Licensed\x20u\
    nder\x20the\x20Apache\x20License,\x20Version\x202.0\x20(the\x20\"License\
    \");\n\x20you\x20may\x20not\x20use\x20this\x20file\x20except\x20in\x20co\
    mpliance\x20with\x20the\x20License.\n\x20You\x20may\x20obtain\x20a\x20co\
    py\x20of\x20the\x20License\x20at\n\n\x20\x20\x20\x20\x20http://www.apach\
    e.org/licenses/LICENSE-2.0\n\n\x20Unless\x20required\x20by\x20applicable\
    \x20law\x20or\x20agreed\x20to\x20in\x20writing,\x20software\n\x20distrib\
    uted\x20under\x20the\x20License\x20is\x20distributed\x20on\x20an\x20\"AS\
    \x20IS\"\x20BASIS,\n\x20WITHOUT\x20WARRANTIES\x20OR\x20CONDITIONS\x20OF\
    \x20ANY\x20KIND,\x20either\x20express\x20or\x20implied.\n\x20See\x20the\
    \x20License\x20for\x20the\x20specific\x20language\x20governing\x20permis\
    sions\x20and\n\x20limitations\x20under\x20the\x20License.\n\n\x08\n\x01\
    \x02\x12\x03\x10\0'\n\t\n\x02\x03\0\x12\x03\x12\04\n\t\n\x02\x03\x01\x12\
    \x03\x13\0)\n\x08\n\x01\x08\x12\x03\x15\0;\n\t\n\x02\x08%\x12\x03\x15\0;\
    \n\x08\n\x01\x08\x12\x03\x16\0a\n\t\n\x02\x08\x0b\x12\x03\x16\0a\n\x08\n\
    \x01\x08\x12\x03\x17\0\"\n\t\n\x02\x08\n\x12\x03\x17\0\"\n\x08\n\x01\x08\
    \x12\x03\x18\0/\n\t\n\x02\x08\x08\x12\x03\x18\0/\n\x08\n\x01\x08\x12\x03\
    \x19\0;\n\t\n\x02\x08\x01\x12\x03\x19\0;\n\x08\n\x01\x08\x12\x03\x1a\0;\
    \n\t\n\x02\x08)\x12\x03\x1a\0;\n\x08\n\x01\x08\x12\x03\x1b\0:\n\t\n\x02\
    \x08-\x12\x03\x1b\0:\n4\n\x02\x04\0\x12\x04\x1e\0/\x01\x1a(\x20Container\
    \x20associated\x20with\x20the\x20finding.\n\n\n\n\x03\x04\0\x01\x12\x03\
    \x1e\x08\x11\n%\n\x04\x04\0\x02\0\x12\x03\x20\x02\x12\x1a\x18\x20Name\
    \x20of\x20the\x20container.\n\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x20\
    \x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x20\t\r\n\x0c\n\x05\x04\0\
    \x02\0\x03\x12\x03\x20\x10\x11\n\x99\x01\n\x04\x04\0\x02\x01\x12\x03$\
    \x02\x11\x1a\x8b\x01\x20Container\x20image\x20URI\x20provided\x20when\
    \x20configuring\x20a\x20pod\x20or\x20container.\x20This\n\x20string\x20c\
    an\x20identify\x20a\x20container\x20image\x20version\x20using\x20mutable\
    \x20tags.\n\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03$\x02\x08\n\x0c\n\x05\
    \x04\0\x02\x01\x01\x12\x03$\t\x0c\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03$\
    \x0f\x10\n\xa4\x01\n\x04\x04\0\x02\x02\x12\x03(\x02\x16\x1a\x96\x01\x20O\
    ptional\x20container\x20image\x20ID,\x20if\x20provided\x20by\x20the\x20c\
    ontainer\x20runtime.\x20Uniquely\n\x20identifies\x20the\x20container\x20\
    image\x20launched\x20using\x20a\x20container\x20image\x20digest.\n\n\x0c\
    \n\x05\x04\0\x02\x02\x05\x12\x03(\x02\x08\n\x0c\n\x05\x04\0\x02\x02\x01\
    \x12\x03(\t\x11\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03(\x14\x15\nF\n\x04\
    \x04\0\x02\x03\x12\x03+\x02\x1c\x1a9\x20Container\x20labels,\x20as\x20pr\
    ovided\x20by\x20the\x20container\x20runtime.\n\n\x0c\n\x05\x04\0\x02\x03\
    \x04\x12\x03+\x02\n\n\x0c\n\x05\x04\0\x02\x03\x06\x12\x03+\x0b\x10\n\x0c\
    \n\x05\x04\0\x02\x03\x01\x12\x03+\x11\x17\n\x0c\n\x05\x04\0\x02\x03\x03\
    \x12\x03+\x1a\x1b\n7\n\x04\x04\0\x02\x04\x12\x03.\x02,\x1a*\x20The\x20ti\
    me\x20that\x20the\x20container\x20was\x20created.\n\n\x0c\n\x05\x04\0\
    \x02\x04\x06\x12\x03.\x02\x1b\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03.\x1c\
    '\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03.*+b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::label::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(Container::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
