// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]


#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `google/cloud/securitycenter/v2/attack_path.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

///  A path that an attacker could take to reach an exposed resource.
// @@protoc_insertion_point(message:google.cloud.securitycenter.v2.AttackPath)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AttackPath {
    // message fields
    ///  The attack path name, for example,
    ///   `organizations/12/simulations/34/valuedResources/56/attackPaths/78`
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.name)
    pub name: ::std::string::String,
    ///  A list of nodes that exist in this attack path.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.path_nodes)
    pub path_nodes: ::std::vec::Vec<attack_path::AttackPathNode>,
    ///  A list of the edges between nodes in this attack path.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.edges)
    pub edges: ::std::vec::Vec<attack_path::AttackPathEdge>,
    // special fields
    // @@protoc_insertion_point(special_field:google.cloud.securitycenter.v2.AttackPath.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AttackPath {
    fn default() -> &'a AttackPath {
        <AttackPath as ::protobuf::Message>::default_instance()
    }
}

impl AttackPath {
    pub fn new() -> AttackPath {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &AttackPath| { &m.name },
            |m: &mut AttackPath| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "path_nodes",
            |m: &AttackPath| { &m.path_nodes },
            |m: &mut AttackPath| { &mut m.path_nodes },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "edges",
            |m: &AttackPath| { &m.edges },
            |m: &mut AttackPath| { &mut m.edges },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AttackPath>(
            "AttackPath",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AttackPath {
    const NAME: &'static str = "AttackPath";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                18 => {
                    self.path_nodes.push(is.read_message()?);
                },
                26 => {
                    self.edges.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        for value in &self.path_nodes {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.edges {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        for v in &self.path_nodes {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        for v in &self.edges {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AttackPath {
        AttackPath::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.path_nodes.clear();
        self.edges.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AttackPath {
        static instance: AttackPath = AttackPath {
            name: ::std::string::String::new(),
            path_nodes: ::std::vec::Vec::new(),
            edges: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AttackPath {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AttackPath").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AttackPath {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AttackPath {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `AttackPath`
pub mod attack_path {
    ///  Represents one point that an attacker passes through in this attack path.
    // @@protoc_insertion_point(message:google.cloud.securitycenter.v2.AttackPath.AttackPathNode)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct AttackPathNode {
        // message fields
        ///  The name of the resource at this point in the attack path.
        ///  The format of the name follows the Cloud Asset Inventory [resource
        ///  name
        ///  format](https://cloud.google.com/asset-inventory/docs/resource-name-format)
        // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.resource)
        pub resource: ::std::string::String,
        ///  The [supported resource
        ///  type](https://cloud.google.com/asset-inventory/docs/supported-asset-types)
        // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.resource_type)
        pub resource_type: ::std::string::String,
        ///  Human-readable name of this resource.
        // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.display_name)
        pub display_name: ::std::string::String,
        ///  The findings associated with this node in the attack path.
        // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.associated_findings)
        pub associated_findings: ::std::vec::Vec<attack_path_node::PathNodeAssociatedFinding>,
        ///  Unique id of the attack path node.
        // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.uuid)
        pub uuid: ::std::string::String,
        ///  A list of attack step nodes that exist in this attack path node.
        // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.attack_steps)
        pub attack_steps: ::std::vec::Vec<attack_path_node::AttackStepNode>,
        // special fields
        // @@protoc_insertion_point(special_field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a AttackPathNode {
        fn default() -> &'a AttackPathNode {
            <AttackPathNode as ::protobuf::Message>::default_instance()
        }
    }

    impl AttackPathNode {
        pub fn new() -> AttackPathNode {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(6);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "resource",
                |m: &AttackPathNode| { &m.resource },
                |m: &mut AttackPathNode| { &mut m.resource },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "resource_type",
                |m: &AttackPathNode| { &m.resource_type },
                |m: &mut AttackPathNode| { &mut m.resource_type },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "display_name",
                |m: &AttackPathNode| { &m.display_name },
                |m: &mut AttackPathNode| { &mut m.display_name },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
                "associated_findings",
                |m: &AttackPathNode| { &m.associated_findings },
                |m: &mut AttackPathNode| { &mut m.associated_findings },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "uuid",
                |m: &AttackPathNode| { &m.uuid },
                |m: &mut AttackPathNode| { &mut m.uuid },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
                "attack_steps",
                |m: &AttackPathNode| { &m.attack_steps },
                |m: &mut AttackPathNode| { &mut m.attack_steps },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AttackPathNode>(
                "AttackPath.AttackPathNode",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for AttackPathNode {
        const NAME: &'static str = "AttackPathNode";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.resource = is.read_string()?;
                    },
                    18 => {
                        self.resource_type = is.read_string()?;
                    },
                    26 => {
                        self.display_name = is.read_string()?;
                    },
                    34 => {
                        self.associated_findings.push(is.read_message()?);
                    },
                    42 => {
                        self.uuid = is.read_string()?;
                    },
                    50 => {
                        self.attack_steps.push(is.read_message()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if !self.resource.is_empty() {
                my_size += ::protobuf::rt::string_size(1, &self.resource);
            }
            if !self.resource_type.is_empty() {
                my_size += ::protobuf::rt::string_size(2, &self.resource_type);
            }
            if !self.display_name.is_empty() {
                my_size += ::protobuf::rt::string_size(3, &self.display_name);
            }
            for value in &self.associated_findings {
                let len = value.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            };
            if !self.uuid.is_empty() {
                my_size += ::protobuf::rt::string_size(5, &self.uuid);
            }
            for value in &self.attack_steps {
                let len = value.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            };
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if !self.resource.is_empty() {
                os.write_string(1, &self.resource)?;
            }
            if !self.resource_type.is_empty() {
                os.write_string(2, &self.resource_type)?;
            }
            if !self.display_name.is_empty() {
                os.write_string(3, &self.display_name)?;
            }
            for v in &self.associated_findings {
                ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
            };
            if !self.uuid.is_empty() {
                os.write_string(5, &self.uuid)?;
            }
            for v in &self.attack_steps {
                ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
            };
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> AttackPathNode {
            AttackPathNode::new()
        }

        fn clear(&mut self) {
            self.resource.clear();
            self.resource_type.clear();
            self.display_name.clear();
            self.associated_findings.clear();
            self.uuid.clear();
            self.attack_steps.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static AttackPathNode {
            static instance: AttackPathNode = AttackPathNode {
                resource: ::std::string::String::new(),
                resource_type: ::std::string::String::new(),
                display_name: ::std::string::String::new(),
                associated_findings: ::std::vec::Vec::new(),
                uuid: ::std::string::String::new(),
                attack_steps: ::std::vec::Vec::new(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for AttackPathNode {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("AttackPath.AttackPathNode").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for AttackPathNode {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for AttackPathNode {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }

    /// Nested message and enums of message `AttackPathNode`
    pub mod attack_path_node {
        ///  A finding that is associated with this node in the attack path.
        // @@protoc_insertion_point(message:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.PathNodeAssociatedFinding)
        #[derive(PartialEq,Clone,Default,Debug)]
        pub struct PathNodeAssociatedFinding {
            // message fields
            ///  Canonical name of the associated findings. Example:
            ///  `organizations/123/sources/456/findings/789`
            // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.PathNodeAssociatedFinding.canonical_finding)
            pub canonical_finding: ::std::string::String,
            ///  The additional taxonomy group within findings from a given source.
            // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.PathNodeAssociatedFinding.finding_category)
            pub finding_category: ::std::string::String,
            ///  Full resource name of the finding.
            // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.PathNodeAssociatedFinding.name)
            pub name: ::std::string::String,
            // special fields
            // @@protoc_insertion_point(special_field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.PathNodeAssociatedFinding.special_fields)
            pub special_fields: ::protobuf::SpecialFields,
        }

        impl<'a> ::std::default::Default for &'a PathNodeAssociatedFinding {
            fn default() -> &'a PathNodeAssociatedFinding {
                <PathNodeAssociatedFinding as ::protobuf::Message>::default_instance()
            }
        }

        impl PathNodeAssociatedFinding {
            pub fn new() -> PathNodeAssociatedFinding {
                ::std::default::Default::default()
            }

            pub(in super::super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
                let mut fields = ::std::vec::Vec::with_capacity(3);
                let mut oneofs = ::std::vec::Vec::with_capacity(0);
                fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                    "canonical_finding",
                    |m: &PathNodeAssociatedFinding| { &m.canonical_finding },
                    |m: &mut PathNodeAssociatedFinding| { &mut m.canonical_finding },
                ));
                fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                    "finding_category",
                    |m: &PathNodeAssociatedFinding| { &m.finding_category },
                    |m: &mut PathNodeAssociatedFinding| { &mut m.finding_category },
                ));
                fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                    "name",
                    |m: &PathNodeAssociatedFinding| { &m.name },
                    |m: &mut PathNodeAssociatedFinding| { &mut m.name },
                ));
                ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PathNodeAssociatedFinding>(
                    "AttackPath.AttackPathNode.PathNodeAssociatedFinding",
                    fields,
                    oneofs,
                )
            }
        }

        impl ::protobuf::Message for PathNodeAssociatedFinding {
            const NAME: &'static str = "PathNodeAssociatedFinding";

            fn is_initialized(&self) -> bool {
                true
            }

            fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
                while let Some(tag) = is.read_raw_tag_or_eof()? {
                    match tag {
                        10 => {
                            self.canonical_finding = is.read_string()?;
                        },
                        18 => {
                            self.finding_category = is.read_string()?;
                        },
                        26 => {
                            self.name = is.read_string()?;
                        },
                        tag => {
                            ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                        },
                    };
                }
                ::std::result::Result::Ok(())
            }

            // Compute sizes of nested messages
            #[allow(unused_variables)]
            fn compute_size(&self) -> u64 {
                let mut my_size = 0;
                if !self.canonical_finding.is_empty() {
                    my_size += ::protobuf::rt::string_size(1, &self.canonical_finding);
                }
                if !self.finding_category.is_empty() {
                    my_size += ::protobuf::rt::string_size(2, &self.finding_category);
                }
                if !self.name.is_empty() {
                    my_size += ::protobuf::rt::string_size(3, &self.name);
                }
                my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
                self.special_fields.cached_size().set(my_size as u32);
                my_size
            }

            fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
                if !self.canonical_finding.is_empty() {
                    os.write_string(1, &self.canonical_finding)?;
                }
                if !self.finding_category.is_empty() {
                    os.write_string(2, &self.finding_category)?;
                }
                if !self.name.is_empty() {
                    os.write_string(3, &self.name)?;
                }
                os.write_unknown_fields(self.special_fields.unknown_fields())?;
                ::std::result::Result::Ok(())
            }

            fn special_fields(&self) -> &::protobuf::SpecialFields {
                &self.special_fields
            }

            fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
                &mut self.special_fields
            }

            fn new() -> PathNodeAssociatedFinding {
                PathNodeAssociatedFinding::new()
            }

            fn clear(&mut self) {
                self.canonical_finding.clear();
                self.finding_category.clear();
                self.name.clear();
                self.special_fields.clear();
            }

            fn default_instance() -> &'static PathNodeAssociatedFinding {
                static instance: PathNodeAssociatedFinding = PathNodeAssociatedFinding {
                    canonical_finding: ::std::string::String::new(),
                    finding_category: ::std::string::String::new(),
                    name: ::std::string::String::new(),
                    special_fields: ::protobuf::SpecialFields::new(),
                };
                &instance
            }
        }

        impl ::protobuf::MessageFull for PathNodeAssociatedFinding {
            fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
                static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
                descriptor.get(|| super::super::file_descriptor().message_by_package_relative_name("AttackPath.AttackPathNode.PathNodeAssociatedFinding").unwrap()).clone()
            }
        }

        impl ::std::fmt::Display for PathNodeAssociatedFinding {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                ::protobuf::text_format::fmt(self, f)
            }
        }

        impl ::protobuf::reflect::ProtobufValue for PathNodeAssociatedFinding {
            type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
        }

        ///  Detailed steps the attack can take between path nodes.
        // @@protoc_insertion_point(message:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.AttackStepNode)
        #[derive(PartialEq,Clone,Default,Debug)]
        pub struct AttackStepNode {
            // message fields
            ///  Unique ID for one Node
            // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.AttackStepNode.uuid)
            pub uuid: ::std::string::String,
            ///  Attack step type. Can be either AND, OR or DEFENSE
            // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.AttackStepNode.type)
            pub type_: ::protobuf::EnumOrUnknown<NodeType>,
            ///  User friendly name of the attack step
            // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.AttackStepNode.display_name)
            pub display_name: ::std::string::String,
            ///  Attack step labels for metadata
            // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.AttackStepNode.labels)
            pub labels: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
            ///  Attack step description
            // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.AttackStepNode.description)
            pub description: ::std::string::String,
            // special fields
            // @@protoc_insertion_point(special_field:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.AttackStepNode.special_fields)
            pub special_fields: ::protobuf::SpecialFields,
        }

        impl<'a> ::std::default::Default for &'a AttackStepNode {
            fn default() -> &'a AttackStepNode {
                <AttackStepNode as ::protobuf::Message>::default_instance()
            }
        }

        impl AttackStepNode {
            pub fn new() -> AttackStepNode {
                ::std::default::Default::default()
            }

            pub(in super::super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
                let mut fields = ::std::vec::Vec::with_capacity(5);
                let mut oneofs = ::std::vec::Vec::with_capacity(0);
                fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                    "uuid",
                    |m: &AttackStepNode| { &m.uuid },
                    |m: &mut AttackStepNode| { &mut m.uuid },
                ));
                fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                    "type",
                    |m: &AttackStepNode| { &m.type_ },
                    |m: &mut AttackStepNode| { &mut m.type_ },
                ));
                fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                    "display_name",
                    |m: &AttackStepNode| { &m.display_name },
                    |m: &mut AttackStepNode| { &mut m.display_name },
                ));
                fields.push(::protobuf::reflect::rt::v2::make_map_simpler_accessor::<_, _, _>(
                    "labels",
                    |m: &AttackStepNode| { &m.labels },
                    |m: &mut AttackStepNode| { &mut m.labels },
                ));
                fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                    "description",
                    |m: &AttackStepNode| { &m.description },
                    |m: &mut AttackStepNode| { &mut m.description },
                ));
                ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AttackStepNode>(
                    "AttackPath.AttackPathNode.AttackStepNode",
                    fields,
                    oneofs,
                )
            }
        }

        impl ::protobuf::Message for AttackStepNode {
            const NAME: &'static str = "AttackStepNode";

            fn is_initialized(&self) -> bool {
                true
            }

            fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
                while let Some(tag) = is.read_raw_tag_or_eof()? {
                    match tag {
                        10 => {
                            self.uuid = is.read_string()?;
                        },
                        16 => {
                            self.type_ = is.read_enum_or_unknown()?;
                        },
                        26 => {
                            self.display_name = is.read_string()?;
                        },
                        34 => {
                            let len = is.read_raw_varint32()?;
                            let old_limit = is.push_limit(len as u64)?;
                            let mut key = ::std::default::Default::default();
                            let mut value = ::std::default::Default::default();
                            while let Some(tag) = is.read_raw_tag_or_eof()? {
                                match tag {
                                    10 => key = is.read_string()?,
                                    18 => value = is.read_string()?,
                                    _ => ::protobuf::rt::skip_field_for_tag(tag, is)?,
                                };
                            }
                            is.pop_limit(old_limit);
                            self.labels.insert(key, value);
                        },
                        42 => {
                            self.description = is.read_string()?;
                        },
                        tag => {
                            ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                        },
                    };
                }
                ::std::result::Result::Ok(())
            }

            // Compute sizes of nested messages
            #[allow(unused_variables)]
            fn compute_size(&self) -> u64 {
                let mut my_size = 0;
                if !self.uuid.is_empty() {
                    my_size += ::protobuf::rt::string_size(1, &self.uuid);
                }
                if self.type_ != ::protobuf::EnumOrUnknown::new(NodeType::NODE_TYPE_UNSPECIFIED) {
                    my_size += ::protobuf::rt::int32_size(2, self.type_.value());
                }
                if !self.display_name.is_empty() {
                    my_size += ::protobuf::rt::string_size(3, &self.display_name);
                }
                for (k, v) in &self.labels {
                    let mut entry_size = 0;
                    entry_size += ::protobuf::rt::string_size(1, &k);
                    entry_size += ::protobuf::rt::string_size(2, &v);
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(entry_size) + entry_size
                };
                if !self.description.is_empty() {
                    my_size += ::protobuf::rt::string_size(5, &self.description);
                }
                my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
                self.special_fields.cached_size().set(my_size as u32);
                my_size
            }

            fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
                if !self.uuid.is_empty() {
                    os.write_string(1, &self.uuid)?;
                }
                if self.type_ != ::protobuf::EnumOrUnknown::new(NodeType::NODE_TYPE_UNSPECIFIED) {
                    os.write_enum(2, ::protobuf::EnumOrUnknown::value(&self.type_))?;
                }
                if !self.display_name.is_empty() {
                    os.write_string(3, &self.display_name)?;
                }
                for (k, v) in &self.labels {
                    let mut entry_size = 0;
                    entry_size += ::protobuf::rt::string_size(1, &k);
                    entry_size += ::protobuf::rt::string_size(2, &v);
                    os.write_raw_varint32(34)?; // Tag.
                    os.write_raw_varint32(entry_size as u32)?;
                    os.write_string(1, &k)?;
                    os.write_string(2, &v)?;
                };
                if !self.description.is_empty() {
                    os.write_string(5, &self.description)?;
                }
                os.write_unknown_fields(self.special_fields.unknown_fields())?;
                ::std::result::Result::Ok(())
            }

            fn special_fields(&self) -> &::protobuf::SpecialFields {
                &self.special_fields
            }

            fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
                &mut self.special_fields
            }

            fn new() -> AttackStepNode {
                AttackStepNode::new()
            }

            fn clear(&mut self) {
                self.uuid.clear();
                self.type_ = ::protobuf::EnumOrUnknown::new(NodeType::NODE_TYPE_UNSPECIFIED);
                self.display_name.clear();
                self.labels.clear();
                self.description.clear();
                self.special_fields.clear();
            }

            fn default_instance() -> &'static AttackStepNode {
                static instance: ::protobuf::rt::Lazy<AttackStepNode> = ::protobuf::rt::Lazy::new();
                instance.get(AttackStepNode::new)
            }
        }

        impl ::protobuf::MessageFull for AttackStepNode {
            fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
                static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
                descriptor.get(|| super::super::file_descriptor().message_by_package_relative_name("AttackPath.AttackPathNode.AttackStepNode").unwrap()).clone()
            }
        }

        impl ::std::fmt::Display for AttackStepNode {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                ::protobuf::text_format::fmt(self, f)
            }
        }

        impl ::protobuf::reflect::ProtobufValue for AttackStepNode {
            type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
        }

        ///  The type of the incoming attack step node.
        #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
        // @@protoc_insertion_point(enum:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.NodeType)
        pub enum NodeType {
            // @@protoc_insertion_point(enum_value:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.NodeType.NODE_TYPE_UNSPECIFIED)
            NODE_TYPE_UNSPECIFIED = 0,
            // @@protoc_insertion_point(enum_value:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.NodeType.NODE_TYPE_AND)
            NODE_TYPE_AND = 1,
            // @@protoc_insertion_point(enum_value:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.NodeType.NODE_TYPE_OR)
            NODE_TYPE_OR = 2,
            // @@protoc_insertion_point(enum_value:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.NodeType.NODE_TYPE_DEFENSE)
            NODE_TYPE_DEFENSE = 3,
            // @@protoc_insertion_point(enum_value:google.cloud.securitycenter.v2.AttackPath.AttackPathNode.NodeType.NODE_TYPE_ATTACKER)
            NODE_TYPE_ATTACKER = 4,
        }

        impl ::protobuf::Enum for NodeType {
            const NAME: &'static str = "NodeType";

            fn value(&self) -> i32 {
                *self as i32
            }

            fn from_i32(value: i32) -> ::std::option::Option<NodeType> {
                match value {
                    0 => ::std::option::Option::Some(NodeType::NODE_TYPE_UNSPECIFIED),
                    1 => ::std::option::Option::Some(NodeType::NODE_TYPE_AND),
                    2 => ::std::option::Option::Some(NodeType::NODE_TYPE_OR),
                    3 => ::std::option::Option::Some(NodeType::NODE_TYPE_DEFENSE),
                    4 => ::std::option::Option::Some(NodeType::NODE_TYPE_ATTACKER),
                    _ => ::std::option::Option::None
                }
            }

            fn from_str(str: &str) -> ::std::option::Option<NodeType> {
                match str {
                    "NODE_TYPE_UNSPECIFIED" => ::std::option::Option::Some(NodeType::NODE_TYPE_UNSPECIFIED),
                    "NODE_TYPE_AND" => ::std::option::Option::Some(NodeType::NODE_TYPE_AND),
                    "NODE_TYPE_OR" => ::std::option::Option::Some(NodeType::NODE_TYPE_OR),
                    "NODE_TYPE_DEFENSE" => ::std::option::Option::Some(NodeType::NODE_TYPE_DEFENSE),
                    "NODE_TYPE_ATTACKER" => ::std::option::Option::Some(NodeType::NODE_TYPE_ATTACKER),
                    _ => ::std::option::Option::None
                }
            }

            const VALUES: &'static [NodeType] = &[
                NodeType::NODE_TYPE_UNSPECIFIED,
                NodeType::NODE_TYPE_AND,
                NodeType::NODE_TYPE_OR,
                NodeType::NODE_TYPE_DEFENSE,
                NodeType::NODE_TYPE_ATTACKER,
            ];
        }

        impl ::protobuf::EnumFull for NodeType {
            fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
                static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
                descriptor.get(|| super::super::file_descriptor().enum_by_package_relative_name("AttackPath.AttackPathNode.NodeType").unwrap()).clone()
            }

            fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
                let index = *self as usize;
                Self::enum_descriptor().value_by_index(index)
            }
        }

        impl ::std::default::Default for NodeType {
            fn default() -> Self {
                NodeType::NODE_TYPE_UNSPECIFIED
            }
        }

        impl NodeType {
            pub(in super::super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
                ::protobuf::reflect::GeneratedEnumDescriptorData::new::<NodeType>("AttackPath.AttackPathNode.NodeType")
            }
        }
    }

    ///  Represents a connection between a source node and a destination node in
    ///  this attack path.
    // @@protoc_insertion_point(message:google.cloud.securitycenter.v2.AttackPath.AttackPathEdge)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct AttackPathEdge {
        // message fields
        ///  The attack node uuid of the source node.
        // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathEdge.source)
        pub source: ::std::string::String,
        ///  The attack node uuid of the destination node.
        // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.AttackPath.AttackPathEdge.destination)
        pub destination: ::std::string::String,
        // special fields
        // @@protoc_insertion_point(special_field:google.cloud.securitycenter.v2.AttackPath.AttackPathEdge.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a AttackPathEdge {
        fn default() -> &'a AttackPathEdge {
            <AttackPathEdge as ::protobuf::Message>::default_instance()
        }
    }

    impl AttackPathEdge {
        pub fn new() -> AttackPathEdge {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(2);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "source",
                |m: &AttackPathEdge| { &m.source },
                |m: &mut AttackPathEdge| { &mut m.source },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
                "destination",
                |m: &AttackPathEdge| { &m.destination },
                |m: &mut AttackPathEdge| { &mut m.destination },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AttackPathEdge>(
                "AttackPath.AttackPathEdge",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for AttackPathEdge {
        const NAME: &'static str = "AttackPathEdge";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.source = is.read_string()?;
                    },
                    18 => {
                        self.destination = is.read_string()?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if !self.source.is_empty() {
                my_size += ::protobuf::rt::string_size(1, &self.source);
            }
            if !self.destination.is_empty() {
                my_size += ::protobuf::rt::string_size(2, &self.destination);
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if !self.source.is_empty() {
                os.write_string(1, &self.source)?;
            }
            if !self.destination.is_empty() {
                os.write_string(2, &self.destination)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> AttackPathEdge {
            AttackPathEdge::new()
        }

        fn clear(&mut self) {
            self.source.clear();
            self.destination.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static AttackPathEdge {
            static instance: AttackPathEdge = AttackPathEdge {
                source: ::std::string::String::new(),
                destination: ::std::string::String::new(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for AttackPathEdge {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("AttackPath.AttackPathEdge").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for AttackPathEdge {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for AttackPathEdge {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n0google/cloud/securitycenter/v2/attack_path.proto\x12\x1egoogle.cloud.\
    securitycenter.v2\x1a\x19google/api/resource.proto\"\xce\x0c\n\nAttackPa\
    th\x12\x12\n\x04name\x18\x01\x20\x01(\tR\x04name\x12X\n\npath_nodes\x18\
    \x02\x20\x03(\x0b29.google.cloud.securitycenter.v2.AttackPath.AttackPath\
    NodeR\tpathNodes\x12O\n\x05edges\x18\x03\x20\x03(\x0b29.google.cloud.sec\
    uritycenter.v2.AttackPath.AttackPathEdgeR\x05edges\x1a\xee\x07\n\x0eAtta\
    ckPathNode\x12\x1a\n\x08resource\x18\x01\x20\x01(\tR\x08resource\x12#\n\
    \rresource_type\x18\x02\x20\x01(\tR\x0cresourceType\x12!\n\x0cdisplay_na\
    me\x18\x03\x20\x01(\tR\x0bdisplayName\x12\x84\x01\n\x13associated_findin\
    gs\x18\x04\x20\x03(\x0b2S.google.cloud.securitycenter.v2.AttackPath.Atta\
    ckPathNode.PathNodeAssociatedFindingR\x12associatedFindings\x12\x12\n\
    \x04uuid\x18\x05\x20\x01(\tR\x04uuid\x12k\n\x0cattack_steps\x18\x06\x20\
    \x03(\x0b2H.google.cloud.securitycenter.v2.AttackPath.AttackPathNode.Att\
    ackStepNodeR\x0battackSteps\x1a\x87\x01\n\x19PathNodeAssociatedFinding\
    \x12+\n\x11canonical_finding\x18\x01\x20\x01(\tR\x10canonicalFinding\x12\
    )\n\x10finding_category\x18\x02\x20\x01(\tR\x0ffindingCategory\x12\x12\n\
    \x04name\x18\x03\x20\x01(\tR\x04name\x1a\xea\x02\n\x0eAttackStepNode\x12\
    \x12\n\x04uuid\x18\x01\x20\x01(\tR\x04uuid\x12V\n\x04type\x18\x02\x20\
    \x01(\x0e2B.google.cloud.securitycenter.v2.AttackPath.AttackPathNode.Nod\
    eTypeR\x04type\x12!\n\x0cdisplay_name\x18\x03\x20\x01(\tR\x0bdisplayName\
    \x12l\n\x06labels\x18\x04\x20\x03(\x0b2T.google.cloud.securitycenter.v2.\
    AttackPath.AttackPathNode.AttackStepNode.LabelsEntryR\x06labels\x12\x20\
    \n\x0bdescription\x18\x05\x20\x01(\tR\x0bdescription\x1a9\n\x0bLabelsEnt\
    ry\x12\x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x12\x14\n\x05value\x18\
    \x02\x20\x01(\tR\x05value:\x028\x01\"y\n\x08NodeType\x12\x19\n\x15NODE_T\
    YPE_UNSPECIFIED\x10\0\x12\x11\n\rNODE_TYPE_AND\x10\x01\x12\x10\n\x0cNODE\
    _TYPE_OR\x10\x02\x12\x15\n\x11NODE_TYPE_DEFENSE\x10\x03\x12\x16\n\x12NOD\
    E_TYPE_ATTACKER\x10\x04\x1aJ\n\x0eAttackPathEdge\x12\x16\n\x06source\x18\
    \x01\x20\x01(\tR\x06source\x12\x20\n\x0bdestination\x18\x02\x20\x01(\tR\
    \x0bdestination:\xc3\x02\xeaA\xbf\x02\n(securitycenter.googleapis.com/At\
    tackPath\x12qorganizations/{organization}/simulations/{simulation}/value\
    dResources/{valued_resource}/attackPaths/{attack_path}\x12\x86\x01organi\
    zations/{organization}/locations/{location}/simulations/{simulation}/val\
    uedResources/{valued_resource}/attackPaths/{attack_path}*\x0battackPaths\
    2\nattackPathB\xe9\x01\n\"com.google.cloud.securitycenter.v2B\x0fAttackP\
    athProtoP\x01ZJcloud.google.com/go/securitycenter/apiv2/securitycenterpb\
    ;securitycenterpb\xaa\x02\x1eGoogle.Cloud.SecurityCenter.V2\xca\x02\x1eG\
    oogle\\Cloud\\SecurityCenter\\V2\xea\x02!Google::Cloud::SecurityCenter::\
    V2J\xd3!\n\x07\x12\x05\x0e\0\x83\x01\x01\n\xbc\x04\n\x01\x0c\x12\x03\x0e\
    \0\x122\xb1\x04\x20Copyright\x202024\x20Google\x20LLC\n\n\x20Licensed\
    \x20under\x20the\x20Apache\x20License,\x20Version\x202.0\x20(the\x20\"Li\
    cense\");\n\x20you\x20may\x20not\x20use\x20this\x20file\x20except\x20in\
    \x20compliance\x20with\x20the\x20License.\n\x20You\x20may\x20obtain\x20a\
    \x20copy\x20of\x20the\x20License\x20at\n\n\x20\x20\x20\x20\x20http://www\
    .apache.org/licenses/LICENSE-2.0\n\n\x20Unless\x20required\x20by\x20appl\
    icable\x20law\x20or\x20agreed\x20to\x20in\x20writing,\x20software\n\x20d\
    istributed\x20under\x20the\x20License\x20is\x20distributed\x20on\x20an\
    \x20\"AS\x20IS\"\x20BASIS,\n\x20WITHOUT\x20WARRANTIES\x20OR\x20CONDITION\
    S\x20OF\x20ANY\x20KIND,\x20either\x20express\x20or\x20implied.\n\x20See\
    \x20the\x20License\x20for\x20the\x20specific\x20language\x20governing\
    \x20permissions\x20and\n\x20limitations\x20under\x20the\x20License.\n\n\
    \x08\n\x01\x02\x12\x03\x10\0'\n\t\n\x02\x03\0\x12\x03\x12\0#\n\x08\n\x01\
    \x08\x12\x03\x14\0;\n\t\n\x02\x08%\x12\x03\x14\0;\n\x08\n\x01\x08\x12\
    \x03\x15\0a\n\t\n\x02\x08\x0b\x12\x03\x15\0a\n\x08\n\x01\x08\x12\x03\x16\
    \0\"\n\t\n\x02\x08\n\x12\x03\x16\0\"\n\x08\n\x01\x08\x12\x03\x17\00\n\t\
    \n\x02\x08\x08\x12\x03\x17\00\n\x08\n\x01\x08\x12\x03\x18\0;\n\t\n\x02\
    \x08\x01\x12\x03\x18\0;\n\x08\n\x01\x08\x12\x03\x19\0;\n\t\n\x02\x08)\
    \x12\x03\x19\0;\n\x08\n\x01\x08\x12\x03\x1a\0:\n\t\n\x02\x08-\x12\x03\
    \x1a\0:\nO\n\x02\x04\0\x12\x05\x1d\0\x83\x01\x01\x1aB\x20A\x20path\x20th\
    at\x20an\x20attacker\x20could\x20take\x20to\x20reach\x20an\x20exposed\
    \x20resource.\n\n\n\n\x03\x04\0\x01\x12\x03\x1d\x08\x12\n\x0b\n\x03\x04\
    \0\x07\x12\x04\x1e\x02$\x04\n\r\n\x05\x04\0\x07\x9d\x08\x12\x04\x1e\x02$\
    \x04\nY\n\x04\x04\0\x03\0\x12\x04'\x02n\x03\x1aK\x20Represents\x20one\
    \x20point\x20that\x20an\x20attacker\x20passes\x20through\x20in\x20this\
    \x20attack\x20path.\n\n\x0c\n\x05\x04\0\x03\0\x01\x12\x03'\n\x18\nQ\n\
    \x06\x04\0\x03\0\x03\0\x12\x04)\x043\x05\x1aA\x20A\x20finding\x20that\
    \x20is\x20associated\x20with\x20this\x20node\x20in\x20the\x20attack\x20p\
    ath.\n\n\x0e\n\x07\x04\0\x03\0\x03\0\x01\x12\x03)\x0c%\nt\n\x08\x04\0\
    \x03\0\x03\0\x02\0\x12\x03,\x06#\x1ac\x20Canonical\x20name\x20of\x20the\
    \x20associated\x20findings.\x20Example:\n\x20`organizations/123/sources/\
    456/findings/789`\n\n\x10\n\t\x04\0\x03\0\x03\0\x02\0\x05\x12\x03,\x06\
    \x0c\n\x10\n\t\x04\0\x03\0\x03\0\x02\0\x01\x12\x03,\r\x1e\n\x10\n\t\x04\
    \0\x03\0\x03\0\x02\0\x03\x12\x03,!\"\nU\n\x08\x04\0\x03\0\x03\0\x02\x01\
    \x12\x03/\x06\"\x1aD\x20The\x20additional\x20taxonomy\x20group\x20within\
    \x20findings\x20from\x20a\x20given\x20source.\n\n\x10\n\t\x04\0\x03\0\
    \x03\0\x02\x01\x05\x12\x03/\x06\x0c\n\x10\n\t\x04\0\x03\0\x03\0\x02\x01\
    \x01\x12\x03/\r\x1d\n\x10\n\t\x04\0\x03\0\x03\0\x02\x01\x03\x12\x03/\x20\
    !\n5\n\x08\x04\0\x03\0\x03\0\x02\x02\x12\x032\x06\x16\x1a$\x20Full\x20re\
    source\x20name\x20of\x20the\x20finding.\n\n\x10\n\t\x04\0\x03\0\x03\0\
    \x02\x02\x05\x12\x032\x06\x0c\n\x10\n\t\x04\0\x03\0\x03\0\x02\x02\x01\
    \x12\x032\r\x11\n\x10\n\t\x04\0\x03\0\x03\0\x02\x02\x03\x12\x032\x14\x15\
    \n<\n\x06\x04\0\x03\0\x04\0\x12\x046\x04E\x05\x1a,\x20The\x20type\x20of\
    \x20the\x20incoming\x20attack\x20step\x20node.\n\n\x0e\n\x07\x04\0\x03\0\
    \x04\0\x01\x12\x036\t\x11\n%\n\x08\x04\0\x03\0\x04\0\x02\0\x12\x038\x06\
    \x20\x1a\x14\x20Type\x20not\x20specified\n\n\x10\n\t\x04\0\x03\0\x04\0\
    \x02\0\x01\x12\x038\x06\x1b\n\x10\n\t\x04\0\x03\0\x04\0\x02\0\x02\x12\
    \x038\x1e\x1f\n0\n\x08\x04\0\x03\0\x04\0\x02\x01\x12\x03;\x06\x18\x1a\
    \x1f\x20Incoming\x20edge\x20joined\x20with\x20AND\n\n\x10\n\t\x04\0\x03\
    \0\x04\0\x02\x01\x01\x12\x03;\x06\x13\n\x10\n\t\x04\0\x03\0\x04\0\x02\
    \x01\x02\x12\x03;\x16\x17\n/\n\x08\x04\0\x03\0\x04\0\x02\x02\x12\x03>\
    \x06\x17\x1a\x1e\x20Incoming\x20edge\x20joined\x20with\x20OR\n\n\x10\n\t\
    \x04\0\x03\0\x04\0\x02\x02\x01\x12\x03>\x06\x12\n\x10\n\t\x04\0\x03\0\
    \x04\0\x02\x02\x02\x12\x03>\x15\x16\n+\n\x08\x04\0\x03\0\x04\0\x02\x03\
    \x12\x03A\x06\x1c\x1a\x1a\x20Incoming\x20edge\x20is\x20defense\n\n\x10\n\
    \t\x04\0\x03\0\x04\0\x02\x03\x01\x12\x03A\x06\x17\n\x10\n\t\x04\0\x03\0\
    \x04\0\x02\x03\x02\x12\x03A\x1a\x1b\n,\n\x08\x04\0\x03\0\x04\0\x02\x04\
    \x12\x03D\x06\x1d\x1a\x1b\x20Incoming\x20edge\x20is\x20attacker\n\n\x10\
    \n\t\x04\0\x03\0\x04\0\x02\x04\x01\x12\x03D\x06\x18\n\x10\n\t\x04\0\x03\
    \0\x04\0\x02\x04\x02\x12\x03D\x1b\x1c\nH\n\x06\x04\0\x03\0\x03\x01\x12\
    \x04H\x04W\x05\x1a8\x20Detailed\x20steps\x20the\x20attack\x20can\x20take\
    \x20between\x20path\x20nodes.\n\n\x0e\n\x07\x04\0\x03\0\x03\x01\x01\x12\
    \x03H\x0c\x1a\n)\n\x08\x04\0\x03\0\x03\x01\x02\0\x12\x03J\x06\x16\x1a\
    \x18\x20Unique\x20ID\x20for\x20one\x20Node\n\n\x10\n\t\x04\0\x03\0\x03\
    \x01\x02\0\x05\x12\x03J\x06\x0c\n\x10\n\t\x04\0\x03\0\x03\x01\x02\0\x01\
    \x12\x03J\r\x11\n\x10\n\t\x04\0\x03\0\x03\x01\x02\0\x03\x12\x03J\x14\x15\
    \nE\n\x08\x04\0\x03\0\x03\x01\x02\x01\x12\x03M\x06\x18\x1a4\x20Attack\
    \x20step\x20type.\x20Can\x20be\x20either\x20AND,\x20OR\x20or\x20DEFENSE\
    \n\n\x10\n\t\x04\0\x03\0\x03\x01\x02\x01\x06\x12\x03M\x06\x0e\n\x10\n\t\
    \x04\0\x03\0\x03\x01\x02\x01\x01\x12\x03M\x0f\x13\n\x10\n\t\x04\0\x03\0\
    \x03\x01\x02\x01\x03\x12\x03M\x16\x17\n8\n\x08\x04\0\x03\0\x03\x01\x02\
    \x02\x12\x03P\x06\x1e\x1a'\x20User\x20friendly\x20name\x20of\x20the\x20a\
    ttack\x20step\n\n\x10\n\t\x04\0\x03\0\x03\x01\x02\x02\x05\x12\x03P\x06\
    \x0c\n\x10\n\t\x04\0\x03\0\x03\x01\x02\x02\x01\x12\x03P\r\x19\n\x10\n\t\
    \x04\0\x03\0\x03\x01\x02\x02\x03\x12\x03P\x1c\x1d\n2\n\x08\x04\0\x03\0\
    \x03\x01\x02\x03\x12\x03S\x06%\x1a!\x20Attack\x20step\x20labels\x20for\
    \x20metadata\n\n\x10\n\t\x04\0\x03\0\x03\x01\x02\x03\x06\x12\x03S\x06\
    \x19\n\x10\n\t\x04\0\x03\0\x03\x01\x02\x03\x01\x12\x03S\x1a\x20\n\x10\n\
    \t\x04\0\x03\0\x03\x01\x02\x03\x03\x12\x03S#$\n*\n\x08\x04\0\x03\0\x03\
    \x01\x02\x04\x12\x03V\x06\x1d\x1a\x19\x20Attack\x20step\x20description\n\
    \n\x10\n\t\x04\0\x03\0\x03\x01\x02\x04\x05\x12\x03V\x06\x0c\n\x10\n\t\
    \x04\0\x03\0\x03\x01\x02\x04\x01\x12\x03V\r\x18\n\x10\n\t\x04\0\x03\0\
    \x03\x01\x02\x04\x03\x12\x03V\x1b\x1c\n\xe3\x01\n\x06\x04\0\x03\0\x02\0\
    \x12\x03]\x04\x18\x1a\xd3\x01\x20The\x20name\x20of\x20the\x20resource\
    \x20at\x20this\x20point\x20in\x20the\x20attack\x20path.\n\x20The\x20form\
    at\x20of\x20the\x20name\x20follows\x20the\x20Cloud\x20Asset\x20Inventory\
    \x20[resource\n\x20name\n\x20format](https://cloud.google.com/asset-inve\
    ntory/docs/resource-name-format)\n\n\x0e\n\x07\x04\0\x03\0\x02\0\x05\x12\
    \x03]\x04\n\n\x0e\n\x07\x04\0\x03\0\x02\0\x01\x12\x03]\x0b\x13\n\x0e\n\
    \x07\x04\0\x03\0\x02\0\x03\x12\x03]\x16\x17\nt\n\x06\x04\0\x03\0\x02\x01\
    \x12\x03a\x04\x1d\x1ae\x20The\x20[supported\x20resource\n\x20type](https\
    ://cloud.google.com/asset-inventory/docs/supported-asset-types)\n\n\x0e\
    \n\x07\x04\0\x03\0\x02\x01\x05\x12\x03a\x04\n\n\x0e\n\x07\x04\0\x03\0\
    \x02\x01\x01\x12\x03a\x0b\x18\n\x0e\n\x07\x04\0\x03\0\x02\x01\x03\x12\
    \x03a\x1b\x1c\n6\n\x06\x04\0\x03\0\x02\x02\x12\x03d\x04\x1c\x1a'\x20Huma\
    n-readable\x20name\x20of\x20this\x20resource.\n\n\x0e\n\x07\x04\0\x03\0\
    \x02\x02\x05\x12\x03d\x04\n\n\x0e\n\x07\x04\0\x03\0\x02\x02\x01\x12\x03d\
    \x0b\x17\n\x0e\n\x07\x04\0\x03\0\x02\x02\x03\x12\x03d\x1a\x1b\nK\n\x06\
    \x04\0\x03\0\x02\x03\x12\x03g\x04?\x1a<\x20The\x20findings\x20associated\
    \x20with\x20this\x20node\x20in\x20the\x20attack\x20path.\n\n\x0e\n\x07\
    \x04\0\x03\0\x02\x03\x04\x12\x03g\x04\x0c\n\x0e\n\x07\x04\0\x03\0\x02\
    \x03\x06\x12\x03g\r&\n\x0e\n\x07\x04\0\x03\0\x02\x03\x01\x12\x03g':\n\
    \x0e\n\x07\x04\0\x03\0\x02\x03\x03\x12\x03g=>\n3\n\x06\x04\0\x03\0\x02\
    \x04\x12\x03j\x04\x14\x1a$\x20Unique\x20id\x20of\x20the\x20attack\x20pat\
    h\x20node.\n\n\x0e\n\x07\x04\0\x03\0\x02\x04\x05\x12\x03j\x04\n\n\x0e\n\
    \x07\x04\0\x03\0\x02\x04\x01\x12\x03j\x0b\x0f\n\x0e\n\x07\x04\0\x03\0\
    \x02\x04\x03\x12\x03j\x12\x13\nQ\n\x06\x04\0\x03\0\x02\x05\x12\x03m\x04-\
    \x1aB\x20A\x20list\x20of\x20attack\x20step\x20nodes\x20that\x20exist\x20\
    in\x20this\x20attack\x20path\x20node.\n\n\x0e\n\x07\x04\0\x03\0\x02\x05\
    \x04\x12\x03m\x04\x0c\n\x0e\n\x07\x04\0\x03\0\x02\x05\x06\x12\x03m\r\x1b\
    \n\x0e\n\x07\x04\0\x03\0\x02\x05\x01\x12\x03m\x1c(\n\x0e\n\x07\x04\0\x03\
    \0\x02\x05\x03\x12\x03m+,\nj\n\x04\x04\0\x03\x01\x12\x04r\x02x\x03\x1a\\\
    \x20Represents\x20a\x20connection\x20between\x20a\x20source\x20node\x20a\
    nd\x20a\x20destination\x20node\x20in\n\x20this\x20attack\x20path.\n\n\
    \x0c\n\x05\x04\0\x03\x01\x01\x12\x03r\n\x18\n9\n\x06\x04\0\x03\x01\x02\0\
    \x12\x03t\x04\x16\x1a*\x20The\x20attack\x20node\x20uuid\x20of\x20the\x20\
    source\x20node.\n\n\x0e\n\x07\x04\0\x03\x01\x02\0\x05\x12\x03t\x04\n\n\
    \x0e\n\x07\x04\0\x03\x01\x02\0\x01\x12\x03t\x0b\x11\n\x0e\n\x07\x04\0\
    \x03\x01\x02\0\x03\x12\x03t\x14\x15\n>\n\x06\x04\0\x03\x01\x02\x01\x12\
    \x03w\x04\x1b\x1a/\x20The\x20attack\x20node\x20uuid\x20of\x20the\x20dest\
    ination\x20node.\n\n\x0e\n\x07\x04\0\x03\x01\x02\x01\x05\x12\x03w\x04\n\
    \n\x0e\n\x07\x04\0\x03\x01\x02\x01\x01\x12\x03w\x0b\x16\n\x0e\n\x07\x04\
    \0\x03\x01\x02\x01\x03\x12\x03w\x19\x1a\nw\n\x04\x04\0\x02\0\x12\x03|\
    \x02\x12\x1aj\x20The\x20attack\x20path\x20name,\x20for\x20example,\n\x20\
    \x20`organizations/12/simulations/34/valuedResources/56/attackPaths/78`\
    \n\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03|\x02\x08\n\x0c\n\x05\x04\0\x02\0\
    \x01\x12\x03|\t\r\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03|\x10\x11\n>\n\x04\
    \x04\0\x02\x01\x12\x03\x7f\x02)\x1a1\x20A\x20list\x20of\x20nodes\x20that\
    \x20exist\x20in\x20this\x20attack\x20path.\n\n\x0c\n\x05\x04\0\x02\x01\
    \x04\x12\x03\x7f\x02\n\n\x0c\n\x05\x04\0\x02\x01\x06\x12\x03\x7f\x0b\x19\
    \n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x7f\x1a$\n\x0c\n\x05\x04\0\x02\
    \x01\x03\x12\x03\x7f'(\nF\n\x04\x04\0\x02\x02\x12\x04\x82\x01\x02$\x1a8\
    \x20A\x20list\x20of\x20the\x20edges\x20between\x20nodes\x20in\x20this\
    \x20attack\x20path.\n\n\r\n\x05\x04\0\x02\x02\x04\x12\x04\x82\x01\x02\n\
    \n\r\n\x05\x04\0\x02\x02\x06\x12\x04\x82\x01\x0b\x19\n\r\n\x05\x04\0\x02\
    \x02\x01\x12\x04\x82\x01\x1a\x1f\n\r\n\x05\x04\0\x02\x02\x03\x12\x04\x82\
    \x01\"#b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::resource::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(5);
            messages.push(AttackPath::generated_message_descriptor_data());
            messages.push(attack_path::AttackPathNode::generated_message_descriptor_data());
            messages.push(attack_path::AttackPathEdge::generated_message_descriptor_data());
            messages.push(attack_path::attack_path_node::PathNodeAssociatedFinding::generated_message_descriptor_data());
            messages.push(attack_path::attack_path_node::AttackStepNode::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(attack_path::attack_path_node::NodeType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
