// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]


#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `google/cloud/securitycenter/v2/cloud_dlp_inspection.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

///  Details about the Cloud Data Loss Prevention (Cloud DLP) [inspection
///  job](https://cloud.google.com/dlp/docs/concepts-job-triggers) that produced
///  the finding.
// @@protoc_insertion_point(message:google.cloud.securitycenter.v2.CloudDlpInspection)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CloudDlpInspection {
    // message fields
    ///  Name of the inspection job, for example,
    ///  `projects/123/locations/europe/dlpJobs/i-8383929`.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.CloudDlpInspection.inspect_job)
    pub inspect_job: ::std::string::String,
    ///  The type of information (or
    ///  *[infoType](https://cloud.google.com/dlp/docs/infotypes-reference)*) found,
    ///  for example, `EMAIL_ADDRESS` or `STREET_ADDRESS`.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.CloudDlpInspection.info_type)
    pub info_type: ::std::string::String,
    ///  The number of times Cloud DLP found this infoType within this job
    ///  and resource.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.CloudDlpInspection.info_type_count)
    pub info_type_count: i64,
    ///  Whether Cloud DLP scanned the complete resource or a sampled subset.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.CloudDlpInspection.full_scan)
    pub full_scan: bool,
    // special fields
    // @@protoc_insertion_point(special_field:google.cloud.securitycenter.v2.CloudDlpInspection.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CloudDlpInspection {
    fn default() -> &'a CloudDlpInspection {
        <CloudDlpInspection as ::protobuf::Message>::default_instance()
    }
}

impl CloudDlpInspection {
    pub fn new() -> CloudDlpInspection {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "inspect_job",
            |m: &CloudDlpInspection| { &m.inspect_job },
            |m: &mut CloudDlpInspection| { &mut m.inspect_job },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "info_type",
            |m: &CloudDlpInspection| { &m.info_type },
            |m: &mut CloudDlpInspection| { &mut m.info_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "info_type_count",
            |m: &CloudDlpInspection| { &m.info_type_count },
            |m: &mut CloudDlpInspection| { &mut m.info_type_count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "full_scan",
            |m: &CloudDlpInspection| { &m.full_scan },
            |m: &mut CloudDlpInspection| { &mut m.full_scan },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CloudDlpInspection>(
            "CloudDlpInspection",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CloudDlpInspection {
    const NAME: &'static str = "CloudDlpInspection";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.inspect_job = is.read_string()?;
                },
                18 => {
                    self.info_type = is.read_string()?;
                },
                24 => {
                    self.info_type_count = is.read_int64()?;
                },
                32 => {
                    self.full_scan = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.inspect_job.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.inspect_job);
        }
        if !self.info_type.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.info_type);
        }
        if self.info_type_count != 0 {
            my_size += ::protobuf::rt::int64_size(3, self.info_type_count);
        }
        if self.full_scan != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.inspect_job.is_empty() {
            os.write_string(1, &self.inspect_job)?;
        }
        if !self.info_type.is_empty() {
            os.write_string(2, &self.info_type)?;
        }
        if self.info_type_count != 0 {
            os.write_int64(3, self.info_type_count)?;
        }
        if self.full_scan != false {
            os.write_bool(4, self.full_scan)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CloudDlpInspection {
        CloudDlpInspection::new()
    }

    fn clear(&mut self) {
        self.inspect_job.clear();
        self.info_type.clear();
        self.info_type_count = 0;
        self.full_scan = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CloudDlpInspection {
        static instance: CloudDlpInspection = CloudDlpInspection {
            inspect_job: ::std::string::String::new(),
            info_type: ::std::string::String::new(),
            info_type_count: 0,
            full_scan: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CloudDlpInspection {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CloudDlpInspection").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CloudDlpInspection {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CloudDlpInspection {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n9google/cloud/securitycenter/v2/cloud_dlp_inspection.proto\x12\x1egoog\
    le.cloud.securitycenter.v2\x1a\x19google/api/resource.proto\"\xb7\x01\n\
    \x12CloudDlpInspection\x12?\n\x0binspect_job\x18\x01\x20\x01(\tR\ninspec\
    tJobB\x1e\xfaA\x1b\n\x19dlp.googleapis.com/DlpJob\x12\x1b\n\tinfo_type\
    \x18\x02\x20\x01(\tR\x08infoType\x12&\n\x0finfo_type_count\x18\x03\x20\
    \x01(\x03R\rinfoTypeCount\x12\x1b\n\tfull_scan\x18\x04\x20\x01(\x08R\x08\
    fullScanB\xf0\x02\n\"com.google.cloud.securitycenter.v2B\x17CloudDlpInsp\
    ectionProtoP\x01ZJcloud.google.com/go/securitycenter/apiv2/securitycente\
    rpb;securitycenterpb\xaa\x02\x1eGoogle.Cloud.SecurityCenter.V2\xca\x02\
    \x1eGoogle\\Cloud\\SecurityCenter\\V2\xea\x02!Google::Cloud::SecurityCen\
    ter::V2\xeaA|\n\x19dlp.googleapis.com/DlpJob\x12$projects/{project}/dlpJ\
    obs/{dlp_job}\x129projects/{project}/locations/{location}/dlpJobs/{dlp_j\
    ob}J\xdd\x0c\n\x06\x12\x04\x0e\05\x01\n\xbc\x04\n\x01\x0c\x12\x03\x0e\0\
    \x122\xb1\x04\x20Copyright\x202024\x20Google\x20LLC\n\n\x20Licensed\x20u\
    nder\x20the\x20Apache\x20License,\x20Version\x202.0\x20(the\x20\"License\
    \");\n\x20you\x20may\x20not\x20use\x20this\x20file\x20except\x20in\x20co\
    mpliance\x20with\x20the\x20License.\n\x20You\x20may\x20obtain\x20a\x20co\
    py\x20of\x20the\x20License\x20at\n\n\x20\x20\x20\x20\x20http://www.apach\
    e.org/licenses/LICENSE-2.0\n\n\x20Unless\x20required\x20by\x20applicable\
    \x20law\x20or\x20agreed\x20to\x20in\x20writing,\x20software\n\x20distrib\
    uted\x20under\x20the\x20License\x20is\x20distributed\x20on\x20an\x20\"AS\
    \x20IS\"\x20BASIS,\n\x20WITHOUT\x20WARRANTIES\x20OR\x20CONDITIONS\x20OF\
    \x20ANY\x20KIND,\x20either\x20express\x20or\x20implied.\n\x20See\x20the\
    \x20License\x20for\x20the\x20specific\x20language\x20governing\x20permis\
    sions\x20and\n\x20limitations\x20under\x20the\x20License.\n\n\x08\n\x01\
    \x02\x12\x03\x10\0'\n\t\n\x02\x03\0\x12\x03\x12\0#\n\x08\n\x01\x08\x12\
    \x03\x14\0;\n\t\n\x02\x08%\x12\x03\x14\0;\n\x08\n\x01\x08\x12\x03\x15\0a\
    \n\t\n\x02\x08\x0b\x12\x03\x15\0a\n\x08\n\x01\x08\x12\x03\x16\0\"\n\t\n\
    \x02\x08\n\x12\x03\x16\0\"\n\x08\n\x01\x08\x12\x03\x17\08\n\t\n\x02\x08\
    \x08\x12\x03\x17\08\n\x08\n\x01\x08\x12\x03\x18\0;\n\t\n\x02\x08\x01\x12\
    \x03\x18\0;\n\x08\n\x01\x08\x12\x03\x19\0;\n\t\n\x02\x08)\x12\x03\x19\0;\
    \n\x08\n\x01\x08\x12\x03\x1a\0:\n\t\n\x02\x08-\x12\x03\x1a\0:\n\t\n\x01\
    \x08\x12\x04\x1b\0\x1f\x02\n\x0c\n\x04\x08\x9d\x08\0\x12\x04\x1b\0\x1f\
    \x02\n\xae\x01\n\x02\x04\0\x12\x04$\05\x01\x1a\xa1\x01\x20Details\x20abo\
    ut\x20the\x20Cloud\x20Data\x20Loss\x20Prevention\x20(Cloud\x20DLP)\x20[i\
    nspection\n\x20job](https://cloud.google.com/dlp/docs/concepts-job-trigg\
    ers)\x20that\x20produced\n\x20the\x20finding.\n\n\n\n\x03\x04\0\x01\x12\
    \x03$\x08\x1a\nl\n\x04\x04\0\x02\0\x12\x04'\x02(P\x1a^\x20Name\x20of\x20\
    the\x20inspection\x20job,\x20for\x20example,\n\x20`projects/123/location\
    s/europe/dlpJobs/i-8383929`.\n\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03'\x02\
    \x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03'\t\x14\n\x0c\n\x05\x04\0\x02\0\
    \x03\x12\x03'\x17\x18\n\x0c\n\x05\x04\0\x02\0\x08\x12\x03(\x06O\n\x0e\n\
    \x07\x04\0\x02\0\x08\x9f\x08\x12\x03(\x07N\n\xab\x01\n\x04\x04\0\x02\x01\
    \x12\x03-\x02\x17\x1a\x9d\x01\x20The\x20type\x20of\x20information\x20(or\
    \n\x20*[infoType](https://cloud.google.com/dlp/docs/infotypes-reference)\
    *)\x20found,\n\x20for\x20example,\x20`EMAIL_ADDRESS`\x20or\x20`STREET_AD\
    DRESS`.\n\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03-\x02\x08\n\x0c\n\x05\x04\
    \0\x02\x01\x01\x12\x03-\t\x12\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03-\x15\
    \x16\n_\n\x04\x04\0\x02\x02\x12\x031\x02\x1c\x1aR\x20The\x20number\x20of\
    \x20times\x20Cloud\x20DLP\x20found\x20this\x20infoType\x20within\x20this\
    \x20job\n\x20and\x20resource.\n\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x031\
    \x02\x07\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x031\x08\x17\n\x0c\n\x05\x04\
    \0\x02\x02\x03\x12\x031\x1a\x1b\nS\n\x04\x04\0\x02\x03\x12\x034\x02\x15\
    \x1aF\x20Whether\x20Cloud\x20DLP\x20scanned\x20the\x20complete\x20resour\
    ce\x20or\x20a\x20sampled\x20subset.\n\n\x0c\n\x05\x04\0\x02\x03\x05\x12\
    \x034\x02\x06\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x034\x07\x10\n\x0c\n\x05\
    \x04\0\x02\x03\x03\x12\x034\x13\x14b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::resource::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(CloudDlpInspection::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
