// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]


#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `google/cloud/securitycenter/v2/exfiltration.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

///  Exfiltration represents a data exfiltration attempt from one or more sources
///  to one or more targets. The `sources` attribute lists the sources of the
///  exfiltrated data. The `targets` attribute lists the destinations the data was
///  copied to.
// @@protoc_insertion_point(message:google.cloud.securitycenter.v2.Exfiltration)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Exfiltration {
    // message fields
    ///  If there are multiple sources, then the data is considered "joined" between
    ///  them. For instance, BigQuery can join multiple tables, and each
    ///  table would be considered a source.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.Exfiltration.sources)
    pub sources: ::std::vec::Vec<ExfilResource>,
    ///  If there are multiple targets, each target would get a complete copy of the
    ///  "joined" source data.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.Exfiltration.targets)
    pub targets: ::std::vec::Vec<ExfilResource>,
    ///  Total exfiltrated bytes processed for the entire job.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.Exfiltration.total_exfiltrated_bytes)
    pub total_exfiltrated_bytes: i64,
    // special fields
    // @@protoc_insertion_point(special_field:google.cloud.securitycenter.v2.Exfiltration.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Exfiltration {
    fn default() -> &'a Exfiltration {
        <Exfiltration as ::protobuf::Message>::default_instance()
    }
}

impl Exfiltration {
    pub fn new() -> Exfiltration {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "sources",
            |m: &Exfiltration| { &m.sources },
            |m: &mut Exfiltration| { &mut m.sources },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "targets",
            |m: &Exfiltration| { &m.targets },
            |m: &mut Exfiltration| { &mut m.targets },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "total_exfiltrated_bytes",
            |m: &Exfiltration| { &m.total_exfiltrated_bytes },
            |m: &mut Exfiltration| { &mut m.total_exfiltrated_bytes },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Exfiltration>(
            "Exfiltration",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Exfiltration {
    const NAME: &'static str = "Exfiltration";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.sources.push(is.read_message()?);
                },
                18 => {
                    self.targets.push(is.read_message()?);
                },
                24 => {
                    self.total_exfiltrated_bytes = is.read_int64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.sources {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        for value in &self.targets {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if self.total_exfiltrated_bytes != 0 {
            my_size += ::protobuf::rt::int64_size(3, self.total_exfiltrated_bytes);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.sources {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        for v in &self.targets {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if self.total_exfiltrated_bytes != 0 {
            os.write_int64(3, self.total_exfiltrated_bytes)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Exfiltration {
        Exfiltration::new()
    }

    fn clear(&mut self) {
        self.sources.clear();
        self.targets.clear();
        self.total_exfiltrated_bytes = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Exfiltration {
        static instance: Exfiltration = Exfiltration {
            sources: ::std::vec::Vec::new(),
            targets: ::std::vec::Vec::new(),
            total_exfiltrated_bytes: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Exfiltration {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Exfiltration").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Exfiltration {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Exfiltration {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  Resource where data was exfiltrated from or exfiltrated to.
// @@protoc_insertion_point(message:google.cloud.securitycenter.v2.ExfilResource)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ExfilResource {
    // message fields
    ///  The resource's [full resource
    ///  name](https://cloud.google.com/apis/design/resource_names#full_resource_name).
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.ExfilResource.name)
    pub name: ::std::string::String,
    ///  Subcomponents of the asset that was exfiltrated, like URIs used during
    ///  exfiltration, table names, databases, and filenames. For example, multiple
    ///  tables might have been exfiltrated from the same Cloud SQL instance, or
    ///  multiple files might have been exfiltrated from the same Cloud Storage
    ///  bucket.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.ExfilResource.components)
    pub components: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:google.cloud.securitycenter.v2.ExfilResource.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ExfilResource {
    fn default() -> &'a ExfilResource {
        <ExfilResource as ::protobuf::Message>::default_instance()
    }
}

impl ExfilResource {
    pub fn new() -> ExfilResource {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &ExfilResource| { &m.name },
            |m: &mut ExfilResource| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "components",
            |m: &ExfilResource| { &m.components },
            |m: &mut ExfilResource| { &mut m.components },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ExfilResource>(
            "ExfilResource",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ExfilResource {
    const NAME: &'static str = "ExfilResource";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                18 => {
                    self.components.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        for value in &self.components {
            my_size += ::protobuf::rt::string_size(2, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        for v in &self.components {
            os.write_string(2, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ExfilResource {
        ExfilResource::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.components.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ExfilResource {
        static instance: ExfilResource = ExfilResource {
            name: ::std::string::String::new(),
            components: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ExfilResource {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ExfilResource").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ExfilResource {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ExfilResource {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n1google/cloud/securitycenter/v2/exfiltration.proto\x12\x1egoogle.cloud\
    .securitycenter.v2\"\xd8\x01\n\x0cExfiltration\x12G\n\x07sources\x18\x01\
    \x20\x03(\x0b2-.google.cloud.securitycenter.v2.ExfilResourceR\x07sources\
    \x12G\n\x07targets\x18\x02\x20\x03(\x0b2-.google.cloud.securitycenter.v2\
    .ExfilResourceR\x07targets\x126\n\x17total_exfiltrated_bytes\x18\x03\x20\
    \x01(\x03R\x15totalExfiltratedBytes\"C\n\rExfilResource\x12\x12\n\x04nam\
    e\x18\x01\x20\x01(\tR\x04name\x12\x1e\n\ncomponents\x18\x02\x20\x03(\tR\
    \ncomponentsB\xeb\x01\n\"com.google.cloud.securitycenter.v2B\x11Exfiltra\
    tionProtoP\x01ZJcloud.google.com/go/securitycenter/apiv2/securitycenterp\
    b;securitycenterpb\xaa\x02\x1eGoogle.Cloud.SecurityCenter.V2\xca\x02\x1e\
    Google\\Cloud\\SecurityCenter\\V2\xea\x02!Google::Cloud::SecurityCenter:\
    :V2J\x80\x11\n\x06\x12\x04\x0e\08\x01\n\xbc\x04\n\x01\x0c\x12\x03\x0e\0\
    \x122\xb1\x04\x20Copyright\x202024\x20Google\x20LLC\n\n\x20Licensed\x20u\
    nder\x20the\x20Apache\x20License,\x20Version\x202.0\x20(the\x20\"License\
    \");\n\x20you\x20may\x20not\x20use\x20this\x20file\x20except\x20in\x20co\
    mpliance\x20with\x20the\x20License.\n\x20You\x20may\x20obtain\x20a\x20co\
    py\x20of\x20the\x20License\x20at\n\n\x20\x20\x20\x20\x20http://www.apach\
    e.org/licenses/LICENSE-2.0\n\n\x20Unless\x20required\x20by\x20applicable\
    \x20law\x20or\x20agreed\x20to\x20in\x20writing,\x20software\n\x20distrib\
    uted\x20under\x20the\x20License\x20is\x20distributed\x20on\x20an\x20\"AS\
    \x20IS\"\x20BASIS,\n\x20WITHOUT\x20WARRANTIES\x20OR\x20CONDITIONS\x20OF\
    \x20ANY\x20KIND,\x20either\x20express\x20or\x20implied.\n\x20See\x20the\
    \x20License\x20for\x20the\x20specific\x20language\x20governing\x20permis\
    sions\x20and\n\x20limitations\x20under\x20the\x20License.\n\n\x08\n\x01\
    \x02\x12\x03\x10\0'\n\x08\n\x01\x08\x12\x03\x12\0;\n\t\n\x02\x08%\x12\
    \x03\x12\0;\n\x08\n\x01\x08\x12\x03\x13\0a\n\t\n\x02\x08\x0b\x12\x03\x13\
    \0a\n\x08\n\x01\x08\x12\x03\x14\0\"\n\t\n\x02\x08\n\x12\x03\x14\0\"\n\
    \x08\n\x01\x08\x12\x03\x15\02\n\t\n\x02\x08\x08\x12\x03\x15\02\n\x08\n\
    \x01\x08\x12\x03\x16\0;\n\t\n\x02\x08\x01\x12\x03\x16\0;\n\x08\n\x01\x08\
    \x12\x03\x17\0;\n\t\n\x02\x08)\x12\x03\x17\0;\n\x08\n\x01\x08\x12\x03\
    \x18\0:\n\t\n\x02\x08-\x12\x03\x18\0:\n\x80\x02\n\x02\x04\0\x12\x04\x1e\
    \0*\x01\x1a\xf3\x01\x20Exfiltration\x20represents\x20a\x20data\x20exfilt\
    ration\x20attempt\x20from\x20one\x20or\x20more\x20sources\n\x20to\x20one\
    \x20or\x20more\x20targets.\x20The\x20`sources`\x20attribute\x20lists\x20\
    the\x20sources\x20of\x20the\n\x20exfiltrated\x20data.\x20The\x20`targets\
    `\x20attribute\x20lists\x20the\x20destinations\x20the\x20data\x20was\n\
    \x20copied\x20to.\n\n\n\n\x03\x04\0\x01\x12\x03\x1e\x08\x14\n\xc1\x01\n\
    \x04\x04\0\x02\0\x12\x03\"\x02%\x1a\xb3\x01\x20If\x20there\x20are\x20mul\
    tiple\x20sources,\x20then\x20the\x20data\x20is\x20considered\x20\"joined\
    \"\x20between\n\x20them.\x20For\x20instance,\x20BigQuery\x20can\x20join\
    \x20multiple\x20tables,\x20and\x20each\n\x20table\x20would\x20be\x20cons\
    idered\x20a\x20source.\n\n\x0c\n\x05\x04\0\x02\0\x04\x12\x03\"\x02\n\n\
    \x0c\n\x05\x04\0\x02\0\x06\x12\x03\"\x0b\x18\n\x0c\n\x05\x04\0\x02\0\x01\
    \x12\x03\"\x19\x20\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\"#$\nq\n\x04\x04\
    \0\x02\x01\x12\x03&\x02%\x1ad\x20If\x20there\x20are\x20multiple\x20targe\
    ts,\x20each\x20target\x20would\x20get\x20a\x20complete\x20copy\x20of\x20\
    the\n\x20\"joined\"\x20source\x20data.\n\n\x0c\n\x05\x04\0\x02\x01\x04\
    \x12\x03&\x02\n\n\x0c\n\x05\x04\0\x02\x01\x06\x12\x03&\x0b\x18\n\x0c\n\
    \x05\x04\0\x02\x01\x01\x12\x03&\x19\x20\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03&#$\nD\n\x04\x04\0\x02\x02\x12\x03)\x02$\x1a7\x20Total\x20exfilt\
    rated\x20bytes\x20processed\x20for\x20the\x20entire\x20job.\n\n\x0c\n\
    \x05\x04\0\x02\x02\x05\x12\x03)\x02\x07\n\x0c\n\x05\x04\0\x02\x02\x01\
    \x12\x03)\x08\x1f\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03)\"#\nI\n\x02\x04\
    \x01\x12\x04-\08\x01\x1a=\x20Resource\x20where\x20data\x20was\x20exfiltr\
    ated\x20from\x20or\x20exfiltrated\x20to.\n\n\n\n\x03\x04\x01\x01\x12\x03\
    -\x08\x15\n|\n\x04\x04\x01\x02\0\x12\x030\x02\x12\x1ao\x20The\x20resourc\
    e's\x20[full\x20resource\n\x20name](https://cloud.google.com/apis/design\
    /resource_names#full_resource_name).\n\n\x0c\n\x05\x04\x01\x02\0\x05\x12\
    \x030\x02\x08\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x030\t\r\n\x0c\n\x05\x04\
    \x01\x02\0\x03\x12\x030\x10\x11\n\xbc\x02\n\x04\x04\x01\x02\x01\x12\x037\
    \x02!\x1a\xae\x02\x20Subcomponents\x20of\x20the\x20asset\x20that\x20was\
    \x20exfiltrated,\x20like\x20URIs\x20used\x20during\n\x20exfiltration,\
    \x20table\x20names,\x20databases,\x20and\x20filenames.\x20For\x20example\
    ,\x20multiple\n\x20tables\x20might\x20have\x20been\x20exfiltrated\x20fro\
    m\x20the\x20same\x20Cloud\x20SQL\x20instance,\x20or\n\x20multiple\x20fil\
    es\x20might\x20have\x20been\x20exfiltrated\x20from\x20the\x20same\x20Clo\
    ud\x20Storage\n\x20bucket.\n\n\x0c\n\x05\x04\x01\x02\x01\x04\x12\x037\
    \x02\n\n\x0c\n\x05\x04\x01\x02\x01\x05\x12\x037\x0b\x11\n\x0c\n\x05\x04\
    \x01\x02\x01\x01\x12\x037\x12\x1c\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\
    \x037\x1f\x20b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(Exfiltration::generated_message_descriptor_data());
            messages.push(ExfilResource::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
