// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]


#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `google/cloud/securitycenter/v2/toxic_combination.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

///  Contains details about a group of security issues that, when the issues
///  occur together, represent a greater risk than when the issues occur
///  independently. A group of such issues is referred to as a toxic
///  combination.
// @@protoc_insertion_point(message:google.cloud.securitycenter.v2.ToxicCombination)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ToxicCombination {
    // message fields
    ///  The
    ///  [Attack exposure
    ///  score](https://cloud.google.com/security-command-center/docs/attack-exposure-learn#attack_exposure_scores)
    ///  of this toxic combination. The score is a measure of how much this toxic
    ///  combination exposes one or more high-value resources to potential attack.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.ToxicCombination.attack_exposure_score)
    pub attack_exposure_score: f64,
    ///  List of resource names of findings associated with this toxic combination.
    ///  For example, `organizations/123/sources/456/findings/789`.
    // @@protoc_insertion_point(field:google.cloud.securitycenter.v2.ToxicCombination.related_findings)
    pub related_findings: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:google.cloud.securitycenter.v2.ToxicCombination.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ToxicCombination {
    fn default() -> &'a ToxicCombination {
        <ToxicCombination as ::protobuf::Message>::default_instance()
    }
}

impl ToxicCombination {
    pub fn new() -> ToxicCombination {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "attack_exposure_score",
            |m: &ToxicCombination| { &m.attack_exposure_score },
            |m: &mut ToxicCombination| { &mut m.attack_exposure_score },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "related_findings",
            |m: &ToxicCombination| { &m.related_findings },
            |m: &mut ToxicCombination| { &mut m.related_findings },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ToxicCombination>(
            "ToxicCombination",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ToxicCombination {
    const NAME: &'static str = "ToxicCombination";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                9 => {
                    self.attack_exposure_score = is.read_double()?;
                },
                18 => {
                    self.related_findings.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.attack_exposure_score != 0. {
            my_size += 1 + 8;
        }
        for value in &self.related_findings {
            my_size += ::protobuf::rt::string_size(2, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.attack_exposure_score != 0. {
            os.write_double(1, self.attack_exposure_score)?;
        }
        for v in &self.related_findings {
            os.write_string(2, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ToxicCombination {
        ToxicCombination::new()
    }

    fn clear(&mut self) {
        self.attack_exposure_score = 0.;
        self.related_findings.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ToxicCombination {
        static instance: ToxicCombination = ToxicCombination {
            attack_exposure_score: 0.,
            related_findings: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ToxicCombination {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ToxicCombination").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ToxicCombination {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ToxicCombination {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n6google/cloud/securitycenter/v2/toxic_combination.proto\x12\x1egoogle.\
    cloud.securitycenter.v2\"q\n\x10ToxicCombination\x122\n\x15attack_exposu\
    re_score\x18\x01\x20\x01(\x01R\x13attackExposureScore\x12)\n\x10related_\
    findings\x18\x02\x20\x03(\tR\x0frelatedFindingsB\xef\x01\n\"com.google.c\
    loud.securitycenter.v2B\x15ToxicCombinationProtoP\x01ZJcloud.google.com/\
    go/securitycenter/apiv2/securitycenterpb;securitycenterpb\xaa\x02\x1eGoo\
    gle.Cloud.SecurityCenter.V2\xca\x02\x1eGoogle\\Cloud\\SecurityCenter\\V2\
    \xea\x02!Google::Cloud::SecurityCenter::V2J\x81\x0c\n\x06\x12\x04\x0e\0)\
    \x01\n\xbc\x04\n\x01\x0c\x12\x03\x0e\0\x122\xb1\x04\x20Copyright\x202024\
    \x20Google\x20LLC\n\n\x20Licensed\x20under\x20the\x20Apache\x20License,\
    \x20Version\x202.0\x20(the\x20\"License\");\n\x20you\x20may\x20not\x20us\
    e\x20this\x20file\x20except\x20in\x20compliance\x20with\x20the\x20Licens\
    e.\n\x20You\x20may\x20obtain\x20a\x20copy\x20of\x20the\x20License\x20at\
    \n\n\x20\x20\x20\x20\x20http://www.apache.org/licenses/LICENSE-2.0\n\n\
    \x20Unless\x20required\x20by\x20applicable\x20law\x20or\x20agreed\x20to\
    \x20in\x20writing,\x20software\n\x20distributed\x20under\x20the\x20Licen\
    se\x20is\x20distributed\x20on\x20an\x20\"AS\x20IS\"\x20BASIS,\n\x20WITHO\
    UT\x20WARRANTIES\x20OR\x20CONDITIONS\x20OF\x20ANY\x20KIND,\x20either\x20\
    express\x20or\x20implied.\n\x20See\x20the\x20License\x20for\x20the\x20sp\
    ecific\x20language\x20governing\x20permissions\x20and\n\x20limitations\
    \x20under\x20the\x20License.\n\n\x08\n\x01\x02\x12\x03\x10\0'\n\x08\n\
    \x01\x08\x12\x03\x12\0;\n\t\n\x02\x08%\x12\x03\x12\0;\n\x08\n\x01\x08\
    \x12\x03\x13\0a\n\t\n\x02\x08\x0b\x12\x03\x13\0a\n\x08\n\x01\x08\x12\x03\
    \x14\0\"\n\t\n\x02\x08\n\x12\x03\x14\0\"\n\x08\n\x01\x08\x12\x03\x15\06\
    \n\t\n\x02\x08\x08\x12\x03\x15\06\n\x08\n\x01\x08\x12\x03\x16\0;\n\t\n\
    \x02\x08\x01\x12\x03\x16\0;\n\x08\n\x01\x08\x12\x03\x17\0;\n\t\n\x02\x08\
    )\x12\x03\x17\0;\n\x08\n\x01\x08\x12\x03\x18\0:\n\t\n\x02\x08-\x12\x03\
    \x18\0:\n\xea\x01\n\x02\x04\0\x12\x04\x1e\0)\x01\x1a\xdd\x01\x20Contains\
    \x20details\x20about\x20a\x20group\x20of\x20security\x20issues\x20that,\
    \x20when\x20the\x20issues\n\x20occur\x20together,\x20represent\x20a\x20g\
    reater\x20risk\x20than\x20when\x20the\x20issues\x20occur\n\x20independen\
    tly.\x20A\x20group\x20of\x20such\x20issues\x20is\x20referred\x20to\x20as\
    \x20a\x20toxic\n\x20combination.\n\n\n\n\x03\x04\0\x01\x12\x03\x1e\x08\
    \x18\n\xa6\x02\n\x04\x04\0\x02\0\x12\x03$\x02#\x1a\x98\x02\x20The\n\x20[\
    Attack\x20exposure\n\x20score](https://cloud.google.com/security-command\
    -center/docs/attack-exposure-learn#attack_exposure_scores)\n\x20of\x20th\
    is\x20toxic\x20combination.\x20The\x20score\x20is\x20a\x20measure\x20of\
    \x20how\x20much\x20this\x20toxic\n\x20combination\x20exposes\x20one\x20o\
    r\x20more\x20high-value\x20resources\x20to\x20potential\x20attack.\n\n\
    \x0c\n\x05\x04\0\x02\0\x05\x12\x03$\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\
    \x12\x03$\t\x1e\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03$!\"\n\x96\x01\n\x04\
    \x04\0\x02\x01\x12\x03(\x02'\x1a\x88\x01\x20List\x20of\x20resource\x20na\
    mes\x20of\x20findings\x20associated\x20with\x20this\x20toxic\x20combinat\
    ion.\n\x20For\x20example,\x20`organizations/123/sources/456/findings/789\
    `.\n\n\x0c\n\x05\x04\0\x02\x01\x04\x12\x03(\x02\n\n\x0c\n\x05\x04\0\x02\
    \x01\x05\x12\x03(\x0b\x11\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03(\x12\"\n\
    \x0c\n\x05\x04\0\x02\x01\x03\x12\x03(%&b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(ToxicCombination::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
